/**
 * ui_automap.mjs — the surface map maintains itself.
 *
 * Ryan, 2026-08-03: "we need to set up an automap mechanism, as a new action/screen/whatever
 * is added it auto goes on the map, so we dont have to go back and map things. and it should
 * delete and change as things do."
 *
 * So nothing here is hand-written. The crawler (`ui_map_surfaces.mjs`) discovers groups from
 * `rail-group-*`, members from `surface-member-*`, and every clickable inside whatever
 * container the surface actually rendered into. This module turns that crawl into the
 * committed map, diffs it against the previous one, and — the part that makes it stay true —
 * fails when the two disagree.
 *
 * The reason it needs a guard at all: a doc that is merely *regenerable* still goes stale the
 * first time someone adds a screen and doesn't run the command. The guard is what converts
 * "we can regenerate this" into "this cannot be wrong". That is the same lesson as the
 * duplicated audit doc whose lock test guarded the copy nobody regenerated: it stayed green
 * while the real doc rotted.
 *
 *   node scripts/ui_automap.mjs --check     # no browser: is the committed MD in sync with
 *                                           # the committed JSON? (pre-commit / CI)
 *
 * To refresh from the live app, run the crawler with --sync:
 *   node scripts/ui_map_surfaces.mjs --sync
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const FRONTEND = path.resolve(HERE, "..");
export const REPO = path.resolve(FRONTEND, "..");
export const SNAPSHOT = path.join(FRONTEND, "ui-surface-map.json");
export const DOC = path.join(REPO, "docs", "ide-frontend", "UI_SURFACE_MAP.md");

const GENERATED =
  "<!-- GENERATED by frontend/scripts/ui_map_surfaces.mjs --sync. Do not hand-edit: the guard " +
  "`node scripts/ui_automap.mjs --check` will fail and your edit will be overwritten. -->";

/** Stable identity of a surface, and of an action within it. */
export const surfaceKey = (r) => `${r.group}/${r.member}`;
const actionKey = (a) => a.tid || `label:${a.label}`;

/** Did this surface pass? One place, so the doc, the console and the guard cannot disagree. */
export function verdict(r) {
  const bad = [];
  if (!r.opened) bad.push("NO-OPEN");
  if (!r.changed) bad.push(`NO-NEW-CONTENT(${r.fresh ?? 0})`);
  // `settled` is absent in snapshots taken before the assertion existed; only a literal
  // false is a finding, so an old snapshot does not turn into 33 phantom failures.
  if (r.settled === false) bad.push(`NOT-SETTLED(${r.settleNote || "?"})`);
  if (r.err) bad.push(`ERR:${r.err}`);
  if (r.overlap?.length) bad.push(`OVERLAP x${r.overlap.length}`);
  return { ok: bad.length === 0, bad };
}

/**
 * What changed between two crawls. This is the "auto goes on the map / deletes and changes
 * as things do" part: a new screen shows up as ADDED without anyone listing it, a deleted one
 * disappears, and a surface that grew or lost a button reports the button by name.
 */
export function diffMaps(prev, next) {
  const P = new Map((prev || []).map((r) => [surfaceKey(r), r]));
  const N = new Map((next || []).map((r) => [surfaceKey(r), r]));
  const added = [...N.keys()].filter((k) => !P.has(k));
  const removed = [...P.keys()].filter((k) => !N.has(k));
  const changed = [];

  for (const [k, n] of N) {
    const p = P.get(k);
    if (!p) continue;
    const notes = [];

    const pa = new Set((p.actions || []).map(actionKey));
    const na = new Set((n.actions || []).map(actionKey));
    const gained = [...na].filter((x) => !pa.has(x));
    const lost = [...pa].filter((x) => !na.has(x));
    if (gained.length) notes.push(`+action ${gained.slice(0, 6).join(", ")}`);
    if (lost.length) notes.push(`-action ${lost.slice(0, 6).join(", ")}`);

    const pv = verdict(p);
    const nv = verdict(n);
    if (pv.ok !== nv.ok) notes.push(nv.ok ? "FIXED" : `REGRESSED (${nv.bad.join(" · ")})`);
    else if (pv.bad.join("|") !== nv.bad.join("|")) notes.push(`status ${nv.bad.join(" · ") || "ok"}`);

    if ((p.renderedIn || "") !== (n.renderedIn || "")) {
      notes.push(`renders in ${n.renderedIn || "?"} (was ${p.renderedIn || "?"})`);
    }
    if ((p.modes || []).join(",") !== (n.modes || []).join(",")) {
      notes.push(`opens as ${(n.modes || []).join("/") || "direct"}`);
    }
    if (notes.length) changed.push({ key: k, notes });
  }
  return { added, removed, changed };
}

/** Plain names for the containers a surface can land in. The raw selector is noise in a doc. */
const where = (r) => {
  const s = r.renderedIn || "";
  if (s.includes("settings-modal")) return "modal";
  if (s.includes("hosted-addon")) return "add-on window";
  if (s.includes("workbench-primary-surface")) return "cockpit panel";
  if (s === "unknown" || !s) return "**unrecognised container**";
  return s;
};

/** The committed map. Also the visual board: one row per surface, ✅ or ❌, evidence beside it. */
export function renderMarkdown(map, meta = {}) {
  const L = [];
  const pass = map.filter((r) => verdict(r).ok).length;

  L.push(GENERATED);
  L.push("");
  L.push("# Determinex IDE — Surface Map");
  L.push("");
  L.push(
    "Every group, every surface, what each one **becomes** after the click, and every action " +
      "inside it. Crawled from the running app — the rail is the source of truth, so a screen " +
      "added to the product appears here on the next sync and a deleted one disappears."
  );
  L.push("");
  L.push(`- **Surfaces:** ${map.length} across ${new Set(map.map((r) => r.group)).size} groups`);
  L.push(`- **Clean:** ${pass}/${map.length}`);
  L.push(`- **Window width:** ${meta.width || "native"}`);
  if (meta.generatedAt) L.push(`- **Crawled:** ${meta.generatedAt}`);
  L.push(`- **Regenerate:** \`cd frontend && node scripts/ui_map_surfaces.mjs --sync\``);
  L.push(`- **Guard:** \`cd frontend && node scripts/ui_automap.mjs --check\``);
  L.push("");
  // Deliberately the generic path, never the absolute one from the machine that ran the
  // crawl: this doc is committed, so a local path both leaks the operator's layout and makes
  // the guard fail on a clean tree the moment someone runs it from elsewhere.
  L.push(
    "Screenshots are written to `<tmp>/uimap/<width>/` and are deliberately not committed — 33 " +
      "full-window PNGs per width would outweigh the rest of the frontend. The sync run also " +
      "writes `ui-map-board.html` next to them, which is the same table with the shots inlined " +
      "for eyeballing."
  );
  L.push("");
  L.push("## Surfaces");
  L.push("");
  L.push("| | Group | Surface | Opens as | Renders in | New lines | Actions | Settles | Finding |");
  L.push("|---|---|---|---|---|---|---|---|---|");
  for (const r of map) {
    const v = verdict(r);
    // Time-to-content is reported, not judged. It is the difference between a panel that is
    // right and a panel that is right eventually, and only one of those films well.
    const secs = r.settleMs == null ? "—" : `${(r.settleMs / 1000).toFixed(1)}s`;
    const slow = r.settleMs != null && r.settleMs > 5000 ? ` ⚠️` : "";
    L.push(
      `| ${v.ok ? "✅" : "❌"} | ${r.group} | \`${r.member}\` | ${
        (r.modes || []).join(" / ") || "direct"
      } | ${where(r)} | ${r.fresh ?? 0} | ${(r.actions || []).length} | ${secs}${slow} | ${
        v.ok ? "—" : v.bad.join(" · ")
      } |`
    );
  }
  L.push("");
  const slowOnes = map.filter((r) => r.settleMs != null && r.settleMs > 5000);
  if (slowOnes.length) {
    L.push(
      `⚠️ marks a surface that took over 5s to finish rendering: ` +
        slowOnes
          .map((r) => `\`${surfaceKey(r)}\` (${(r.settleMs / 1000).toFixed(1)}s)`)
          .join(", ") +
        ". These pass — they do render — but they are the ones that look broken on camera."
    );
    L.push("");
  }

  const bad = map.filter((r) => !verdict(r).ok);
  if (bad.length) {
    L.push("## Open findings");
    L.push("");
    for (const r of bad) {
      L.push(`### ${surfaceKey(r)} — ${verdict(r).bad.join(" · ")}`);
      L.push("");
      if (r.overlap?.length) {
        L.push("Overlapping text (the two elements share screen area):");
        L.push("");
        for (const o of r.overlap) L.push(`- \`${o}\``);
        L.push("");
      }
      if (r.err) L.push(`Error text on screen: \`${r.err}\`` + "\n");
      if (r.freshSample?.length) {
        L.push(`First new lines: ${r.freshSample.map((s) => `\`${s}\``).join(", ")}`);
        L.push("");
      }
    }
  }

  L.push("## Action inventory");
  L.push("");
  L.push("What each surface offers once open. A new button appears here without being listed.");
  L.push("");
  for (const r of map) {
    const acts = r.actions || [];
    L.push(`<details><summary><code>${surfaceKey(r)}</code> — ${acts.length} actions</summary>`);
    L.push("");
    if (!acts.length) {
      L.push("_No clickable elements found in the rendered container._");
    } else {
      L.push("| testid | label | tag | disabled |");
      L.push("|---|---|---|---|");
      for (const a of acts) {
        L.push(
          `| ${a.tid ? `\`${a.tid}\`` : "—"} | ${(a.label || "—").replace(/\|/g, "\\|")} | ${
            a.tag
          } | ${a.disabled ? "yes" : ""} |`
        );
      }
    }
    L.push("");
    L.push("</details>");
    L.push("");
  }
  // Exactly ONE trailing newline. The <details> loop leaves a blank line at the end, and
  // pre-commit's end-of-file-fixer strips it — after which this guard compared the file
  // against a render that still had it and failed on a tree nobody had touched. Two guards
  // disagreeing about the same file is worse than either one missing, because the fix for
  // one re-breaks the other forever.
  return L.join("\n").replace(/\n+$/, "") + "\n";
}

/** The eyeball board. Not committed; this is what you actually LOOK at. */
export function renderBoardHtml(map, meta = {}) {
  const rows = map
    .map((r) => {
      const v = verdict(r);
      const shot = `${r.group}__${r.member}.png`;
      return `<section class="${v.ok ? "ok" : "bad"}">
  <h2>${v.ok ? "✅" : "❌"} ${surfaceKey(r)}</h2>
  <p class="meta">opens as <b>${(r.modes || []).join(" / ") || "direct"}</b> ·
     renders in <b>${where(r)}</b> · <b>${r.fresh ?? 0}</b> new lines ·
     <b>${(r.actions || []).length}</b> actions</p>
  ${v.ok ? "" : `<p class="finding">${v.bad.join(" · ")}</p>`}
  ${(r.overlap || []).map((o) => `<p class="ov">${o.replace(/</g, "&lt;")}</p>`).join("")}
  <img loading="lazy" src="${shot}" alt="${surfaceKey(r)}">
</section>`;
    })
    .join("\n");
  const pass = map.filter((r) => verdict(r).ok).length;
  return `<!doctype html><meta charset="utf-8"><title>Determinex surface board</title>
<style>
 body{background:#0b0b10;color:#e7e7ef;font:14px/1.5 system-ui,sans-serif;margin:0;padding:24px}
 h1{font-size:20px} .sum{color:#9aa} section{border:1px solid #24243a;border-radius:10px;
 padding:14px;margin:18px 0;background:#111119} section.bad{border-color:#7a2b2b}
 h2{font-size:16px;margin:0 0 6px} .meta{color:#8d8da8;margin:0 0 8px}
 .finding{color:#ff8a8a;font-weight:600;margin:4px 0}
 .ov{color:#ffc48a;font-family:ui-monospace,monospace;font-size:12px;margin:2px 0}
 img{max-width:100%;border:1px solid #24243a;border-radius:6px;display:block;margin-top:10px}
</style>
<h1>Determinex IDE — surface board</h1>
<p class="sum">${pass}/${map.length} clean · width ${meta.width || "native"} · ${
    meta.generatedAt || ""
  }</p>
${rows}`;
}

export const readSnapshot = () =>
  fs.existsSync(SNAPSHOT) ? JSON.parse(fs.readFileSync(SNAPSHOT, "utf8")) : null;

/** Write the committed pair and report what moved. */
export function sync(map, meta) {
  const prev = readSnapshot();
  const prevMap = Array.isArray(prev) ? prev : prev?.surfaces || null;
  const d = diffMaps(prevMap, map);
  fs.writeFileSync(
    SNAPSHOT,
    // Trailing newline for the same reason: end-of-file-fixer would otherwise add one on
    // every commit and report the file as modified.
    JSON.stringify({ generatedAt: meta.generatedAt, width: meta.width, surfaces: map }, null, 2) +
      "\n"
  );
  fs.mkdirSync(path.dirname(DOC), { recursive: true });
  fs.writeFileSync(DOC, renderMarkdown(map, meta));
  return d;
}

// ---------------------------------------------------------------- guard
if (process.argv.includes("--check")) {
  const snap = readSnapshot();
  if (!snap) {
    console.log(`FAIL  no snapshot at ${SNAPSHOT} — run: node scripts/ui_map_surfaces.mjs --sync`);
    process.exit(1);
  }
  const map = Array.isArray(snap) ? snap : snap.surfaces;
  const meta = Array.isArray(snap) ? {} : { generatedAt: snap.generatedAt, width: snap.width };
  if (!fs.existsSync(DOC)) {
    console.log(`FAIL  ${path.relative(REPO, DOC)} is missing — run the sync.`);
    process.exit(1);
  }
  const onDisk = fs.readFileSync(DOC, "utf8").replace(/\r\n/g, "\n");
  const expect = renderMarkdown(map, meta).replace(/\r\n/g, "\n");
  if (onDisk !== expect) {
    const a = onDisk.split("\n");
    const b = expect.split("\n");
    const i = a.findIndex((l, n) => l !== b[n]);
    console.log(`FAIL  ${path.relative(REPO, DOC)} is not what the snapshot renders.`);
    console.log(`      first difference at line ${i + 1}`);
    console.log(`      doc:      ${JSON.stringify((a[i] || "").slice(0, 100))}`);
    console.log(`      snapshot: ${JSON.stringify((b[i] || "").slice(0, 100))}`);
    console.log(`      fix: cd frontend && node scripts/ui_map_surfaces.mjs --sync`);
    process.exit(1);
  }
  const pass = map.filter((r) => verdict(r).ok).length;
  console.log(`ok    surface map in sync — ${map.length} surfaces, ${pass} clean`);
}
