"""
train_observer.py — Determinex Observer Fine-Tuning Forge (Phase 12b)

Fine-tunes `unsloth/Phi-3-mini-4k-instruct` (4-bit quantized) on Observer DPO
telemetry data generated by the Rust orchestrator's JSONL training logger.

Pipeline:
  1.  Load base model in 4-bit NF4 via Unsloth (zero-copy VRAM loading)
  2.  Inject a LoRA adapter (r=16) for parameter-efficient fine-tuning
  3.  Load the JSONL dataset from the Rust staging directory
  4.  Apply the ShareGPT chat template (system + human + gpt roles)
  5.  Train with SFTTrainer @ lr=2e-4 (Phi-3 sweet-spot from ablation studies)
  6.  Export the merged model as a 16-bit GGUF for Ollama cold-loading

Hardware Target: 6 GB VRAM GPU (Tier 0 — Turing or newer)
  - 4-bit base model load:      ~1.8 GB VRAM
  - LoRA r=16 adapter overhead: ~0.3 GB VRAM
  - Optimizer state headroom:   ~1.2 GB VRAM
  Total training peak:          ~3.3 GB (well within 6GB constraint)

Usage:
    python train_observer.py [--data_path PATH] [--output_dir DIR] [--epochs N]
"""

import argparse
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# CLI ARGS
# ---------------------------------------------------------------------------

parser = argparse.ArgumentParser(description="Determinex Observer fine-tuning forge")
parser.add_argument(
    "--data_path",
    type=str,
    default="../../frontend/src-tauri/.determinex_staging/training_data/observer_dpo.jsonl",
    help="Path to the JSONL training dataset produced by the Rust telemetry logger.",
)
parser.add_argument(
    "--output_dir",
    type=str,
    default="outputs/determinex_observer_gguf",
    help="Directory to write the final merged 16-bit GGUF model.",
)
parser.add_argument(
    "--epochs",
    type=int,
    default=3,
    help="Number of training epochs (default: 3).",
)
parser.add_argument(
    "--max_seq_length",
    type=int,
    default=2048,
    help="Max sequence length. Must match orchestrator num_ctx cap (default: 2048).",
)
parser.add_argument(
    "--per_device_batch_size",
    type=int,
    default=2,
    help="Per-device batch size. Reduce to 1 if GPU OOM occurs on 6GB VRAM.",
)
args = parser.parse_args()

# ---------------------------------------------------------------------------
# DEPENDENCY IMPORTS (deferred so --help works without the full GPU stack)
# ---------------------------------------------------------------------------

print("[FORGE] Importing Unsloth — this may take a moment on first run...", flush=True)
try:
    from unsloth import FastLanguageModel
except ImportError as e:
    sys.exit(
        "[FORGE] FATAL: unsloth not installed.\n"
        "  Run: pip install unsloth[colab-new]\n"
        f"  Detail: {e}"
    )

try:
    from datasets import load_dataset
    from trl import SFTTrainer
    from transformers import TrainingArguments
except ImportError as e:
    sys.exit(
        "[FORGE] FATAL: Missing dependency.\n"
        "  Run: pip install -r requirements.txt\n"
        f"  Detail: {e}"
    )

# ---------------------------------------------------------------------------
# SECURITY: SAFE PATH RESOLVER
# ---------------------------------------------------------------------------

# Resolve a user-supplied path and constrain it to an explicit set of allowed
# parent directories. This prevents CWE-23 Path Traversal via CLI arguments.
# The raw string is joined with a known-safe anchor before Path resolution —
# user input never flows directly into pathlib.Path as a standalone argument.
_SCRIPT_DIR = Path(__file__).resolve().parent
_DETERMINEX_ROOT = _SCRIPT_DIR.parent.parent  # scripts/fine_tuning -> determinex root

# Absolute allowlist of valid parent directories for each argument role.
_ALLOWED_DATA_ROOTS = [
    _DETERMINEX_ROOT,   # data may live anywhere under the determinex repo tree
]
_ALLOWED_OUTPUT_ROOTS = [
    _SCRIPT_DIR,     # outputs must stay local to scripts/fine_tuning/
    _SCRIPT_DIR / "outputs",
]

def safe_resolve(raw_path: str, allowed_roots: list) -> Path:
    """Resolve a CLI-supplied path and validate it against an allowlist of roots.

    Strategy: join with the script dir first so relative inputs like
    'outputs/foo' resolve correctly, then check the absolute result against
    every allowed root. This ensures the raw string never reaches pathlib
    as a standalone unsanitised argument.
    """
    # Anchor relative paths to the script directory to produce a canonical abs path
    candidate = (_SCRIPT_DIR / raw_path).resolve()
    for root in allowed_roots:
        if candidate.is_relative_to(root.resolve()):
            return candidate
    # If anchoring to script dir failed, try anchoring to determinex root
    candidate_from_root = (_DETERMINEX_ROOT / raw_path).resolve()
    for root in allowed_roots:
        if candidate_from_root.is_relative_to(root.resolve()):
            return candidate_from_root
    sys.exit(
        f"[FORGE] FATAL: Path '{raw_path}' resolves outside permitted directories.\n"
        f"  Permitted roots: {[str(r) for r in allowed_roots]}\n"
        f"  Use a relative path anchored inside the Determinex repository."
    )


# ---------------------------------------------------------------------------
# 1. VALIDATE DATASET PATH
# ---------------------------------------------------------------------------

data_path = safe_resolve(args.data_path, _ALLOWED_DATA_ROOTS)
if not data_path.exists():
    sys.exit(
        f"[FORGE] FATAL: Training dataset not found at:\n"
        f"  {data_path}\n"
        f"  Ensure the Rust orchestrator has produced telemetry data before running.\n"
        f"  The Rust staging path is: frontend/src-tauri/.determinex_staging/training_data/"
    )
print(f"[FORGE] Dataset located: {data_path}", flush=True)


# ---------------------------------------------------------------------------
# 2. LOAD BASE MODEL (4-bit NF4 quantized)
# ---------------------------------------------------------------------------

BASE_MODEL = "unsloth/Phi-3-mini-4k-instruct"
MAX_SEQ_LENGTH = args.max_seq_length

print(f"[FORGE] Loading base model: {BASE_MODEL} (4-bit NF4)...", flush=True)

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=BASE_MODEL,
    max_seq_length=MAX_SEQ_LENGTH,
    # dtype=None → Unsloth auto-selects:
    #   bfloat16 on Ampere+ (RTX 3000+)
    #   float16  on Turing  (6 GB Tier 0 GPU) — correct for this hardware target
    dtype=None,
    load_in_4bit=True,  # NF4 quantization: cuts VRAM from ~7.2 GB to ~1.8 GB
)

print("[FORGE] Base model loaded.", flush=True)

# ---------------------------------------------------------------------------
# 3. INJECT LORA ADAPTER (r=16)
# ---------------------------------------------------------------------------
# Target modules are Phi-3's standard attention + MLP projections.
# r=16 / alpha=32 is empirically stable for instruction-tuning on small datasets.
# Gradient checkpointing via Unsloth's patched kernel reduces VRAM by ~40%.

print("[FORGE] Injecting LoRA adapter (r=16, alpha=32)...", flush=True)

model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
    lora_alpha=32,      # 2x rank — standard stable-convergence heuristic
    lora_dropout=0.05,  # Light regularisation to prevent overfitting on small telemetry sets
    bias="none",        # No additional bias params — keeps adapter footprint lean
    # Unsloth's patched gradient checkpointing: ~40% VRAM reduction versus standard HF
    use_gradient_checkpointing="unsloth",
    random_state=42,
)

print("[FORGE] LoRA adapter injected.", flush=True)

# ---------------------------------------------------------------------------
# 4. LOAD AND FORMAT DATASET
# ---------------------------------------------------------------------------
# Expected JSONL schema (ShareGPT format, generated by the Rust telemetry logger):
# {
#   "conversations": [
#     {"role": "system", "value": "<Observer system prompt>"},
#     {"role": "human",  "value": "<code + plan to audit>"},
#     {"role": "gpt",    "value": "{\"verdict\": \"CLEAN\", \"issues\": [], \"confidence\": 0.95}"}
#   ]
# }

print("[FORGE] Loading dataset from JSONL...", flush=True)

raw_dataset = load_dataset(
    "json",
    data_files=str(data_path),
    split="train",
)

print(f"[FORGE] Dataset loaded — {len(raw_dataset)} samples.", flush=True)

# Apply Phi-3 ShareGPT chat template.
# Unsloth standardises the conversational role tokens automatically.
# EOS token is appended at the end of each assistant turn for proper SFT masking.
chat_template = tokenizer.apply_chat_template

def format_conversations(examples):
    """Format each entry via the tokenizer's built-in chat template."""
    formatted = []
    for convo in examples["conversations"]:
        text = tokenizer.apply_chat_template(
            convo,
            tokenize=False,
            add_generation_prompt=False,
        )
        formatted.append(text)
    return {"text": formatted}

print("[FORGE] Applying ShareGPT chat template...", flush=True)
dataset = raw_dataset.map(format_conversations, batched=True)
print("[FORGE] Chat template applied.", flush=True)

# ---------------------------------------------------------------------------
# 5. CONFIGURE SFTTrainer
# ---------------------------------------------------------------------------

output_dir = safe_resolve(args.output_dir, _ALLOWED_OUTPUT_ROOTS)
output_dir.mkdir(parents=True, exist_ok=True)

print(f"[FORGE] Configuring SFTTrainer (lr=2e-4, epochs={args.epochs})...", flush=True)

training_args = TrainingArguments(
    output_dir=str(output_dir / "checkpoints"),
    per_device_train_batch_size=args.per_device_batch_size,
    # Gradient accumulation: effective batch = per_device * grad_accum = 2 * 4 = 8
    # This simulates a larger batch on a constrained 6GB GPU without OOM risk.
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    num_train_epochs=args.epochs,
    lr_scheduler_type="cosine",     # Cosine decay: prevents loss spikes late in training
    warmup_ratio=0.05,              # 5% linear warmup before cosine decay begins
    weight_decay=0.01,
    fp16=not __import__("torch").cuda.is_bf16_supported(),  # float16 on 1660 Ti
    bf16=__import__("torch").cuda.is_bf16_supported(),
    logging_steps=10,
    save_strategy="epoch",
    optim="adamw_8bit",             # 8-bit AdamW: cuts optimizer VRAM by ~50%
    seed=42,
    report_to="none",               # No WandB / MLflow — local forge only
)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=MAX_SEQ_LENGTH,
    dataset_num_proc=2,
    args=training_args,
)

print("[FORGE] Trainer configured.", flush=True)

# ---------------------------------------------------------------------------
# 6. TRAIN
# ---------------------------------------------------------------------------

print("[FORGE] Beginning training run...", flush=True)
trainer_stats = trainer.train()

print(
    f"[FORGE] Training complete.\n"
    f"  Elapsed: {trainer_stats.metrics.get('train_runtime', 0):.1f}s\n"
    f"  Final Loss: {trainer_stats.metrics.get('train_loss', 'N/A')}",
    flush=True,
)

# ---------------------------------------------------------------------------
# 7. EXPORT — 16-bit GGUF for Ollama
# ---------------------------------------------------------------------------
# We merge the LoRA adapter weights back into the base model before quantizing.
# This is MANDATORY for GGUF export — GGUF does not support adapter-delta loading.
#
# q8_0 is the Ollama-preferred GGUF format for a 4k context Phi-3-mini:
#   ~1.8 GB file size, negligible quality loss vs. float16.

print("[FORGE] Merging adapter and exporting to 16-bit GGUF...", flush=True)

model.save_pretrained_gguf(
    str(output_dir),
    tokenizer,
    quantization_method="f16",  # 16-bit full-precision GGUF as specified
)

print(
    f"[FORGE] GGUF export complete.\n"
    f"  Output path: {output_dir.resolve()}\n"
    f"\n"
    f"[FORGE] Next steps:\n"
    f"  1. Verify the GGUF with: ollama run {output_dir.resolve()}/model.gguf\n"
    f"  2. Create a new determinex-observer Modelfile pointing to the exported GGUF\n"
    f"  3. Run: ollama create determinex-observer:v3 -f Modelfile.observer\n",
    flush=True,
)
