"""
train_unsloth.py — Determinex Engineer Fine-Tuning (Standard PEFT)

Replaces Unsloth with standard HuggingFace PEFT — eliminates Windows
dependency hell. Base model: microsoft/Phi-3-mini-4k-instruct (3.8B).

Hardware budget (6 GB VRAM — Tier 0 GPU):
  - Phi-3-mini 4-bit NF4     : ~2.3 GB
  - LoRA r=16 overhead       : ~0.2 GB
  - Gradient checkpointing   : saves ~40% vs no-checkpoint
  - Training peak (batch=1)  : ~3.5–4.0 GB — comfortable headroom on 6 GB

GGUF Export Strategy (in order of attempt):
  1. llama.cpp convert_hf_to_gguf.py + quantize  (if llama.cpp found)
  2. Ollama create from merged HF directory       (Ollama 0.5+ safetensors)
  3. Emit manual-conversion instructions and exit cleanly

Usage:
  python train_unsloth.py [--version N] [--output_dir DIR] [--epochs N]
  python train_unsloth.py --version 4 --per_device_batch_size 1 --max_seq_length 2048
"""

import argparse
import gc
import os
import subprocess
import sys
import time
from pathlib import Path

# Windows cp1252 terminals choke on box-drawing chars — force UTF-8 output
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

# ---------------------------------------------------------------------------
# CLI ARGS
# ---------------------------------------------------------------------------

parser = argparse.ArgumentParser(description="Determinex Engineer fine-tuning (standard PEFT)")
parser.add_argument(
    "--version",
    type=int,
    default=4,
    help="Version number for the output model (e.g. 4 -> determinex-engineer:v4).",
)
parser.add_argument(
    "--output_dir",
    type=str,
    default=None,
    help="Output directory. Defaults to scripts/fine_tuning/outputs/determinex-engineer-vN/",
)
parser.add_argument("--epochs", type=int, default=3, help="Training epochs (default: 3).")
parser.add_argument(
    "--max_seq_length",
    type=int,
    default=2048,
    help="Sequence length. 2048 fits in 6 GB; drop to 1024 if OOM.",
)
parser.add_argument(
    "--per_device_batch_size",
    type=int,
    default=1,
    help="Batch size per GPU. 1 is safe for 6 GB VRAM.",
)
parser.add_argument(
    "--grad_accum",
    type=int,
    default=8,
    help="Gradient accumulation steps (effective batch = batch * grad_accum).",
)
# Catastrophic forgetting mitigation: blend general instruction data alongside curriculum data.
parser.add_argument(
    "--mix-general",
    action="store_true",
    default=False,
    help="Mix general instruction data (alpaca-cleaned) alongside curriculum JSONL "
    "to reduce catastrophic forgetting. Default: off.",
)
parser.add_argument(
    "--curriculum-ratio",
    type=float,
    default=0.8,
    help="Fraction of curriculum data vs general data when --mix-general is on. "
    "E.g., 0.8 = 80%% curriculum, 20%% general. Default: 0.8.",
)
parser.add_argument(
    "--throttle",
    type=float,
    default=0.15,
    help="Seconds to sleep after each gradient step (default: 0.15). "
    "Gives the Windows display compositor GPU time between updates "
    "and prevents the system from hanging during training. "
    "Set 0 to disable. Increase to 0.3-0.5 for heavier throttling.",
)
args = parser.parse_args()

# ---------------------------------------------------------------------------
# PATHS
# ---------------------------------------------------------------------------

_DETERMINEX_ROOT = Path(__file__).resolve().parent
_SRC_TAURI = _DETERMINEX_ROOT / "frontend" / "src-tauri"

DATA_PATHS = [
    _SRC_TAURI / "determinex_v1_distilled_claude.jsonl",
    _SRC_TAURI / "determinex_v1_distilled_gemini.jsonl",
    _SRC_TAURI / "determinex_v1_distilled_observer.jsonl",
    _SRC_TAURI / "determinex_v1_observer_mistakes.jsonl",
    # Generated by scripts/convert_failures_to_sft.py — compile-validated SFT pairs
    # from 276 Immune System failure records. Only present after overnight conversion.
    _SRC_TAURI / "determinex_v1_failures_sft.jsonl",
    # Generated by scripts/generate_gap_curriculum.py — SWE-bench gap coverage:
    # rust_concurrency, rust_interior_mut, go_concurrency, go_panic_recover,
    # python_threading, ts_async_patterns, ts_discriminated + FE_P5 zero-is-even fix.
    _SRC_TAURI / "determinex_v1_gap_curriculum.jsonl",
    # Generated by scripts/generate_gap_curriculum_v2.py — adversarial variants +
    # cpp_smart_pointers (g++ strict) + kotlin_patterns (lenient).
    _SRC_TAURI / "determinex_v1_gap_curriculum_v2.jsonl",
    # Hand-crafted targeted samples for specific micro_eval failures:
    # wrap_error (0/5 → fmt.Errorf %w), go_panic_recover, first_even zero edge case.
    _SRC_TAURI / "determinex_v1_targeted_gaps.jsonl",
]

if args.output_dir is None:
    output_dir = (
        _DETERMINEX_ROOT
        / "scripts"
        / "fine_tuning"
        / "outputs"
        / f"determinex-engineer-v{args.version}"
    )
else:
    output_dir = (_DETERMINEX_ROOT / args.output_dir).resolve()

# Constrain output to within the repo to prevent path traversal
if not str(output_dir).startswith(str(_DETERMINEX_ROOT)):
    sys.exit(f"[FORGE] FATAL: output_dir must be inside the Determinex repo. Got: {output_dir}")

output_dir.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# VALIDATE DATASET
# ---------------------------------------------------------------------------

available = [p for p in DATA_PATHS if p.exists()]
if not available:
    sys.exit(
        "[FORGE] FATAL: No distillation data found.\n"
        "  Looked for:\n"
        + "\n".join(f"    {p}" for p in DATA_PATHS)
        + "\n  Run ignite_forge.ps1 first to generate training data."
    )

total_samples = sum(sum(1 for ln in p.open(encoding="utf-8") if ln.strip()) for p in available)
print(f"[FORGE] Dataset: {total_samples} samples across {len(available)} file(s):", flush=True)
for p in available:
    count = sum(1 for ln in p.open(encoding="utf-8") if ln.strip())
    print(f"  {count:4d}  {p.name}", flush=True)

if total_samples < 5:
    sys.exit(
        f"[FORGE] FATAL: Only {total_samples} samples — too few to train.\n"
        "  Run at least 2-3 forge cycles to accumulate meaningful distillation data."
    )

# ---------------------------------------------------------------------------
# IMPORT GPU STACK
# ---------------------------------------------------------------------------

print("[FORGE] Importing training stack (standard PEFT — no Unsloth)...", flush=True)

try:
    import torch
    from datasets import concatenate_datasets, load_dataset
    from peft import LoraConfig, TaskType, get_peft_model
    from transformers import (
        AutoModelForCausalLM,
        AutoTokenizer,
        BitsAndBytesConfig,
        TrainerCallback,
        TrainerControl,
        TrainerState,
    )
    from trl import SFTConfig, SFTTrainer
except ImportError as e:
    sys.exit(
        f"[FORGE] FATAL: Missing dependency — {e}\n"
        "  Run: pip install transformers peft trl datasets bitsandbytes accelerate"
    )

if not torch.cuda.is_available():
    sys.exit(
        "[FORGE] FATAL: No CUDA GPU detected.\n"
        "  Check: nvidia-smi\n"
        "  Turing/Ampere GPU requires CUDA 11.8+ driver and torch+cu12x."
    )

vram_mb = torch.cuda.get_device_properties(0).total_memory // 1024**2
print(f"[FORGE] GPU: {torch.cuda.get_device_name(0)}  VRAM: {vram_mb} MB", flush=True)

# ---------------------------------------------------------------------------
# 1. LOAD BASE MODEL (4-bit NF4)
# ---------------------------------------------------------------------------
# BitsAndBytesConfig NF4: best quality-per-bit for transformer weights.
# double_quant: nested quantization saves an extra ~0.4 GB.
# compute_dtype float16: Turing-class GPUs do not support bfloat16.

BASE_MODEL = (
    "unsloth/Llama-3.2-3B-Instruct-bnb-4bit"  # pre-quantized, ~2GB download, no VRAM thrash
)
MAX_SEQ_LENGTH = args.max_seq_length

print(f"\n[FORGE] Loading base model: {BASE_MODEL} (4-bit NF4)...", flush=True)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token  # Phi-3 has no dedicated pad token
tokenizer.padding_side = "right"  # left-padding causes training instability

model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
)
model.config.use_cache = False  # must be False for gradient checkpointing
model.enable_input_require_grads()  # required for PEFT + gradient checkpointing
print("[FORGE] Base model loaded.", flush=True)

# ---------------------------------------------------------------------------
# 2. INJECT LoRA ADAPTER
# ---------------------------------------------------------------------------
# r=16 / alpha=32: proven stable for instruction-tuning on small datasets.
# All attention and MLP projections are targeted — full-coverage LoRA.

print("[FORGE] Injecting LoRA adapter (r=16, alpha=32)...", flush=True)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM,
)

model = get_peft_model(model, lora_config)
model.gradient_checkpointing_enable()
model.print_trainable_parameters()
print("[FORGE] LoRA adapter injected.", flush=True)

# ---------------------------------------------------------------------------
# 3. LOAD & MERGE DATASETS
# ---------------------------------------------------------------------------

print("[FORGE] Loading distillation datasets...", flush=True)
raw_datasets = [load_dataset("json", data_files=str(p), split="train") for p in available]
raw_dataset = concatenate_datasets(raw_datasets) if len(raw_datasets) > 1 else raw_datasets[0]

# ---------------------------------------------------------------------------
# ADAPTIVE CURRICULUM FILTER
# If baseline.json exists, skip samples from already-mastered categories.
# Mastery threshold: >= 90% on micro_eval → model already knows this, skip it.
# Unknown categories (no _meta) are always included.
# ---------------------------------------------------------------------------
_BASELINE_PATH = _DETERMINEX_ROOT / "logs" / "eval_results" / "baseline.json"
_CATEGORY_TO_CONCEPT = {
    "rust_concurrency": "arc_mutex",
    "rust_concurrency_adv": "arc_mutex",
    "rust_interior_mut": "refcell_borrow",
    "rust_interior_mut_adv": "refcell_borrow",
    "go_concurrency": "go_fmt_errorf",
    "go_concurrency_adv": "go_fmt_errorf",
    "go_panic_recover": "go_panic_recover",
    "go_panic_recover_adv": "go_panic_recover",
    "go_fmt_errorf": "go_fmt_errorf",
    "python_threading": "safe_divide",
    "python_threading_adv": "safe_divide",
    "first_even_zero": "first_even_zero",
    "targeted_wrap_error": "go_fmt_errorf",
    "targeted_go_panic": "go_panic_recover",
    "targeted_first_even": "first_even_zero",
}
_MASTERY_THRESHOLD = 90

if _BASELINE_PATH.exists():
    try:
        import json as _json

        _baseline = _json.loads(_BASELINE_PATH.read_text(encoding="utf-8"))
        _scores = {
            k: v["score_pct"]
            for k, v in _baseline.get("concepts", _baseline.get("results", {})).items()
        }

        def _is_mastered(sample) -> bool:
            meta = sample.get("_meta") or {}
            if isinstance(meta, str):
                try:
                    meta = _json.loads(meta)
                except:
                    return False
            cat = meta.get("category") or meta.get("source", "")
            concept = _CATEGORY_TO_CONCEPT.get(cat)
            return bool(concept and _scores.get(concept, 0) >= _MASTERY_THRESHOLD)

        _before = len(raw_dataset)
        raw_dataset = raw_dataset.filter(lambda s: not _is_mastered(s))
        _skipped = _before - len(raw_dataset)
        if _skipped:
            print(
                f"[FORGE] Adaptive filter: dropped {_skipped} mastered samples "
                f"(score >= {_MASTERY_THRESHOLD}% on baseline). {len(raw_dataset)} remain.",
                flush=True,
            )
        else:
            print("[FORGE] Adaptive filter: no mastered samples to drop.", flush=True)
    except Exception as _ae:
        print(f"[FORGE] WARNING: adaptive filter failed ({_ae}), using full corpus.", flush=True)
else:
    print(
        "[FORGE] No baseline found — training full corpus. Run micro_eval --save-baseline first.",
        flush=True,
    )

curriculum_len = len(raw_dataset)
print(f"[FORGE] Curriculum samples: {curriculum_len}", flush=True)

# ---------------------------------------------------------------------------
# MIX-GENERAL: Blend alpaca-cleaned to prevent catastrophic forgetting
# ---------------------------------------------------------------------------

if args.mix_general:
    general_target = int(
        curriculum_len * (1.0 - args.curriculum_ratio) / max(args.curriculum_ratio, 0.01)
    )
    print(
        f"[FORGE] --mix-general active: curriculum ratio={args.curriculum_ratio:.0%}  "
        f"target general samples={general_target}",
        flush=True,
    )
    try:
        general_ds = load_dataset(
            "yahma/alpaca-cleaned",
            split=f"train[:{general_target}]",
        )

        # Alpaca format: instruction + input + output -> remap to system/user/assistant
        def remap_alpaca(ex):
            user_ = ex["instruction"]
            if ex.get("input", "").strip():
                user_ = user_ + "\n\n" + ex["input"]
            return {
                "system": "You are a helpful, accurate, and thoughtful AI assistant.",
                "user": user_,
                "assistant": ex.get("output", ""),
            }

        general_ds = general_ds.map(remap_alpaca)
        general_ds = general_ds.select_columns(["system", "user", "assistant"])
        raw_dataset = concatenate_datasets([raw_dataset, general_ds])
        print(
            f"[FORGE] Mixed in {len(general_ds)} general samples. Total: {len(raw_dataset)}",
            flush=True,
        )
    except Exception as e:
        print(
            f"[FORGE] WARNING: --mix-general failed ({e}). Training on curriculum data only.",
            flush=True,
        )
else:
    print(f"[FORGE] Total samples after merge: {curriculum_len}", flush=True)

# ---------------------------------------------------------------------------
# TOKEN PRE-CHECK — discard samples that exceed MAX_SEQ_LENGTH when formatted
# Prevents silent truncation mid-training which corrupts loss computation.
# ---------------------------------------------------------------------------


def _estimate_token_count(sys_p: str, user_p: str, asst_p: str, max_len: int) -> bool:
    """Return True if the formatted sample would fit within max_len tokens."""
    # Approximate: 1 token ≈ 4 chars; use the Llama-3.2 chat template length.
    formatted = (
        f"<|begin_of_text|>"
        f"<|start_header_id|>system<|end_header_id|>\n\n{sys_p}<|eot_id|>"
        f"<|start_header_id|>user<|end_header_id|>\n\n{user_p}<|eot_id|>"
        f"<|start_header_id|>assistant<|end_header_id|>\n\n{asst_p}<|eot_id|>"
    )
    return len(formatted) // 4 <= max_len


pre_check_len = len(raw_dataset)
raw_dataset = raw_dataset.filter(
    lambda ex: _estimate_token_count(
        ex.get("system", ""),
        ex.get("user", ""),
        ex.get("assistant", ""),
        MAX_SEQ_LENGTH,
    ),
    desc="Token pre-check",
)
post_check_len = len(raw_dataset)
if pre_check_len != post_check_len:
    print(
        f"[FORGE] Token pre-check: discarded {pre_check_len - post_check_len} samples "
        f"that exceeded {MAX_SEQ_LENGTH} token limit. "
        f"{post_check_len} samples remain.",
        flush=True,
    )

if len(raw_dataset) < 5:
    sys.exit(
        f"[FORGE] FATAL: Only {len(raw_dataset)} samples after token pre-check. "
        "Generate more training data or increase --max_seq_length."
    )

# ---------------------------------------------------------------------------
# 4. FORMAT PROMPTS — Llama-3.2 instruction format
# ---------------------------------------------------------------------------
# Llama-3.2-Instruct uses special role header tokens.
# This matches what Ollama uses for `llama3.2:3b` inference.


def format_prompts(examples):
    texts = []
    for sys_p, user_p, asst_p in zip(examples["system"], examples["user"], examples["assistant"]):
        text = (
            f"<|begin_of_text|>"
            f"<|start_header_id|>system<|end_header_id|>\n\n{sys_p}<|eot_id|>"
            f"<|start_header_id|>user<|end_header_id|>\n\n{user_p}<|eot_id|>"
            f"<|start_header_id|>assistant<|end_header_id|>\n\n{asst_p}<|eot_id|>"
        )
        texts.append(text)
    return {"text": texts}


print("[FORGE] Applying Llama-3.2 instruction format...", flush=True)
dataset = raw_dataset.map(format_prompts, batched=True)
print("[FORGE] Format applied.", flush=True)

# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# 4b. GPU THROTTLE CALLBACK
# ---------------------------------------------------------------------------
# Sleeps for --throttle seconds after every gradient step.
# On Windows with a single display GPU, sustained 98% utilisation
# starves the Windows compositor of GPU time and causes the display to hang.
# A short sleep per step gives the OS regular windows to push frames.
# Default 0.15s adds ~45s to a 300-step run — an acceptable tradeoff.


class GpuThrottleCallback(TrainerCallback):
    def __init__(self, sleep_secs: float):
        self.sleep_secs = sleep_secs

    def on_step_end(
        self,
        _args,
        _state: TrainerState,
        control: TrainerControl,
        **kwargs,
    ) -> TrainerControl:
        if self.sleep_secs > 0:
            time.sleep(self.sleep_secs)
        return control


_throttle_callbacks = [GpuThrottleCallback(args.throttle)] if args.throttle > 0 else []

if args.throttle > 0:
    print(
        f"[FORGE] GPU throttle: {args.throttle * 1000:.0f}ms sleep per gradient step "
        f"(disable with --throttle 0)",
        flush=True,
    )

# ---------------------------------------------------------------------------
# 5. CONFIGURE SFTTrainer
# ---------------------------------------------------------------------------

checkpoints_dir = output_dir / "checkpoints"
checkpoints_dir.mkdir(parents=True, exist_ok=True)

print(
    f"[FORGE] Configuring trainer "
    f"(lr=2e-4, epochs={args.epochs}, "
    f"batch={args.per_device_batch_size}x{args.grad_accum} grad_accum)...",
    flush=True,
)

sft_config = SFTConfig(
    # SFTConfig-specific (moved out of SFTTrainer in TRL 0.12+; max_seq_length → max_length in 0.24+)
    dataset_text_field="text",
    max_length=MAX_SEQ_LENGTH,
    # Standard TrainingArguments
    output_dir=str(checkpoints_dir),
    per_device_train_batch_size=args.per_device_batch_size,
    gradient_accumulation_steps=args.grad_accum,
    gradient_checkpointing=True,
    learning_rate=2e-4,
    num_train_epochs=args.epochs,
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    weight_decay=0.01,
    fp16=True,  # Turing-class GPUs use float16, not bfloat16
    bf16=False,
    logging_steps=10,
    save_strategy="epoch",
    optim="adamw_8bit",  # 8-bit Adam from bitsandbytes — saves ~1 GB vs standard Adam
    seed=42,
    report_to="none",
    dataloader_pin_memory=False,  # reduces peak VRAM spike on Windows
)

trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=dataset,
    args=sft_config,
    callbacks=_throttle_callbacks or None,
)
print("[FORGE] Trainer ready.", flush=True)

# ---------------------------------------------------------------------------
# 6. TRAIN
# ---------------------------------------------------------------------------

print("\n[FORGE] Beginning neural mutagenesis...", flush=True)
stats = trainer.train()
print(
    f"\n[FORGE] Training complete.\n"
    f"  Runtime : {stats.metrics.get('train_runtime', 0):.1f}s\n"
    f"  Loss    : {stats.metrics.get('train_loss', 'N/A')}",
    flush=True,
)

# ---------------------------------------------------------------------------
# 7. SAVE LoRA ADAPTER
# ---------------------------------------------------------------------------

lora_dir = output_dir / "lora_adapter"
lora_dir.mkdir(exist_ok=True)
model.save_pretrained(str(lora_dir))
tokenizer.save_pretrained(str(lora_dir))
print(f"[FORGE] LoRA adapter saved: {lora_dir}", flush=True)

# ---------------------------------------------------------------------------
# 8. MERGE LoRA INTO BASE MODEL
# ---------------------------------------------------------------------------
# We move the trained PEFT model to CPU BEFORE deleting it, then merge_and_unload.
# This avoids having to reload the base model in FP16 (which would fail for
# pre-quantized bnb-4bit models like unsloth/Llama-3.2-3B-Instruct-bnb-4bit).
# Memory: 3B model on CPU ≈ 6 GB system RAM — well within 19 GB pool.

print("\n[FORGE] Moving trained model to CPU for merge (~1 min)...", flush=True)
merged_dir = None

try:
    # ── Step A: free GPU memory ───────────────────────────────────────────────
    # The 4-bit bnb training model CANNOT be cast to fp16 in-place (bitsandbytes
    # restriction). Delete it to free VRAM, then load a clean fp16 base on CPU.
    del trainer
    del model
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    # ── Step B: load FP16 base on CPU for clean merge ─────────────────────────
    # unsloth/Llama-3.2-3B-Instruct is the non-quantized variant (~6 GB RAM,
    # no VRAM needed — merge happens entirely on CPU).
    MERGE_BASE = "unsloth/Llama-3.2-3B-Instruct"
    print(f"\n[FORGE] Loading FP16 base for merge: {MERGE_BASE}", flush=True)
    print("[FORGE] (CPU-only, ~3–5 min — GPU is free during this step)", flush=True)

    from peft import PeftModel as _PeftModel

    merge_base = AutoModelForCausalLM.from_pretrained(
        MERGE_BASE,
        torch_dtype=torch.float16,
        device_map="cpu",
    )
    print("[FORGE] FP16 base loaded. Applying LoRA adapter...", flush=True)

    peft_for_merge = _PeftModel.from_pretrained(merge_base, str(lora_dir))
    print("[FORGE] Merging LoRA weights into base model...", flush=True)

    merged_model = peft_for_merge.merge_and_unload()
    del merge_base
    del peft_for_merge
    gc.collect()

    merged_dir = output_dir / "merged"
    merged_dir.mkdir(exist_ok=True)
    merged_model.save_pretrained(str(merged_dir), safe_serialization=True)
    tokenizer.save_pretrained(str(merged_dir))
    print(f"[FORGE] Merged FP16 model saved: {merged_dir}", flush=True)

    del merged_model
    gc.collect()

except Exception as e:
    print(f"[FORGE] WARNING: Merge step failed: {e}", flush=True)
    print("[FORGE] LoRA adapter is still saved — merge manually later.", flush=True)

# ---------------------------------------------------------------------------
# 9. GGUF EXPORT
# ---------------------------------------------------------------------------
# Attempt A: llama.cpp convert_hf_to_gguf.py + quantize (best quality)
# Attempt B: Ollama create FROM merged dir (Ollama 0.5+ supports safetensors)
# Fallback:  Print manual-conversion instructions

_llama_env = os.environ.get("LLAMA_CPP_DIR")
LLAMA_CPP_CANDIDATES = [
    *([] if not _llama_env else [Path(_llama_env)]),
    Path("C:/llama.cpp"),
    Path.home() / "llama.cpp",
    Path.home() / "dev" / "llama.cpp",
]

gguf_produced = False
model_tag = f"determinex-engineer:v{args.version}"

if merged_dir and merged_dir.exists():
    # --- Attempt A: llama.cpp ---
    llama_root = next((p for p in LLAMA_CPP_CANDIDATES if p.exists()), None)
    convert_script = (llama_root / "convert_hf_to_gguf.py") if llama_root else None

    if convert_script and convert_script.exists():
        f16_gguf = output_dir / "model-f16.gguf"
        q4_gguf = output_dir / "model.gguf"
        print("\n[FORGE] Running llama.cpp convert_hf_to_gguf.py...", flush=True)

        r = subprocess.run(
            [
                sys.executable,
                str(convert_script),
                str(merged_dir),
                "--outfile",
                str(f16_gguf),
                "--outtype",
                "f16",
            ],
        )
        if r.returncode == 0:
            quantize_candidates = [
                llama_root / "quantize",
                llama_root / "quantize.exe",
                llama_root / "build" / "bin" / "quantize",
                llama_root / "build" / "bin" / "Release" / "llama-quantize.exe",
                llama_root / "build" / "bin" / "llama-quantize",
            ]
            quantize_bin = next((p for p in quantize_candidates if p.exists()), None)
            if quantize_bin:
                r2 = subprocess.run([str(quantize_bin), str(f16_gguf), str(q4_gguf), "Q4_K_M"])
                if r2.returncode == 0:
                    f16_gguf.unlink(missing_ok=True)
                    print(f"[FORGE] GGUF (Q4_K_M): {q4_gguf}", flush=True)
                    gguf_produced = True
                else:
                    # Keep F16 GGUF — still usable, just larger (~14 GB)
                    q4_gguf.rename(q4_gguf.with_suffix(".q4_failed"))
                    print(f"[FORGE] GGUF (F16, quantize failed): {f16_gguf}", flush=True)
                    gguf_produced = True
            else:
                print(f"[FORGE] GGUF (F16, no quantize binary): {f16_gguf}", flush=True)
                gguf_produced = True
        else:
            print("[FORGE] convert_hf_to_gguf.py failed — see output above.", flush=True)

    # --- Attempt B: Ollama create FROM merged dir ---
    if not gguf_produced:
        modelfile_path = _DETERMINEX_ROOT / f"Modelfile.engineer.v{args.version}"
        modelfile_path.write_text(
            f"FROM {merged_dir.as_posix()}\n"
            f"PARAMETER num_ctx {MAX_SEQ_LENGTH}\n"
            f"PARAMETER temperature 0\n",
            encoding="utf-8",
        )
        print("\n[FORGE] Attempting Ollama import from HF directory...", flush=True)
        r = subprocess.run(
            ["ollama", "create", model_tag, "-f", str(modelfile_path)],
            capture_output=True,
            text=True,
        )
        if r.returncode == 0:
            print(f"[FORGE] Ollama imported successfully: {model_tag}", flush=True)
            # Write a marker so ignite_loop.py promote_model() skips the GGUF search
            marker = output_dir / "ollama_promoted.txt"
            marker.write_text(model_tag, encoding="utf-8")
            gguf_produced = True  # model is live in Ollama, treat as promoted
        else:
            print(f"[FORGE] Ollama direct import failed:\n  {r.stderr[:300]}", flush=True)

# ---------------------------------------------------------------------------
# SUMMARY
# ---------------------------------------------------------------------------

print(
    f"\n[FORGE] ============================================\n"
    f"[FORGE] TRAINING COMPLETE\n"
    f"[FORGE] Version  : {model_tag}\n"
    f"[FORGE] LoRA dir : {lora_dir}\n"
    f"[FORGE] Merged   : {merged_dir or 'FAILED (see above)'}\n"
    f"[FORGE] GGUF     : {'Produced (see above)' if gguf_produced else 'Needs manual conversion'}\n"
    f"[FORGE] ============================================",
    flush=True,
)

if not gguf_produced:
    print(
        f"\n[FORGE] Manual GGUF conversion steps:\n"
        f"\n"
        f"  # 1. Clone llama.cpp (one-time):\n"
        f"  git clone https://github.com/ggerganov/llama.cpp ~/llama.cpp\n"
        f"  cd ~/llama.cpp && pip install -r requirements.txt\n"
        f"\n"
        f"  # 2. Convert merged model to F16 GGUF:\n"
        f"  python ~/llama.cpp/convert_hf_to_gguf.py \\\n"
        f"    {merged_dir} --outfile {output_dir}/model-f16.gguf --outtype f16\n"
        f"\n"
        f"  # 3. Quantize to Q4_K_M:\n"
        f"  ~/llama.cpp/build/bin/llama-quantize \\\n"
        f"    {output_dir}/model-f16.gguf {output_dir}/model.gguf Q4_K_M\n"
        f"\n"
        f"  # 4. Register with Ollama:\n"
        f"  ollama create {model_tag} -f Modelfile.engineer.v{args.version}",
        flush=True,
    )
