#!/usr/bin/env python3
"""
determinex_stewardship.py -- project stewardship doc discovery + generation
=============================================================================
Ryan: "the place you are sending everything to, that's there will be the
overall runtime md, and then the project md, if the project doesnt have an
adequate md (or even if they do) the project automatically converts the
stewardship document from the project or in lieu of it not having one,
creates it on the initial scan run so that EVERYTHING stays synced."

Two-tier doc hierarchy the multi-agent chat room's Mission Plan seeds from:
  1. RUNTIME doc -- the root CLAUDE.md ABOVE the workspace (e.g.
     C:\\Dev\\CLAUDE.md governing several projects), found by walking up from
     the workspace looking for an ancestor CLAUDE.md.
  2. PROJECT doc -- the workspace's own CLAUDE.md/PROJECT.md at its root.

If no adequate project doc exists, generate_stewardship_doc() scans the
workspace for real signal (manifest files, top-level structure) and writes a
genuine PROJECT.md -- never a blank placeholder. "Adequate" is a documented
heuristic (non-trivial length), not a claim of quality -- a real "is this
doc good" judgment needs human/model review this module doesn't attempt.

CLI
---
    python scripts/determinex_stewardship.py resolve <workspace> [--json]
    python scripts/determinex_stewardship.py generate <workspace>
"""
from __future__ import annotations

import sys
from pathlib import Path

_ADEQUATE_MIN_CHARS = 300
_ANCESTOR_SEARCH_DEPTH = 6
_MANIFEST_LANGUAGE_MAP = {
    "package.json": "Node.js/TypeScript",
    "pyproject.toml": "Python",
    "requirements.txt": "Python",
    "Cargo.toml": "Rust",
    "go.mod": "Go",
    "pom.xml": "Java (Maven)",
    "build.gradle": "Java/Kotlin (Gradle)",
    "Gemfile": "Ruby",
    "composer.json": "PHP",
}
_SKIP_DIRS = {".git", "node_modules", "__pycache__", ".venv", "venv", "target",
             "dist", "build", ".next", ".pytest_cache"}


def find_runtime_doc(workspace: Path) -> "Path | None":
    """Walk UP from workspace looking for an ancestor CLAUDE.md -- the
    'overall runtime md' that can govern several projects (e.g.
    C:\\Dev\\CLAUDE.md). Never returns the workspace's OWN CLAUDE.md; that's
    the project doc, found separately by find_project_docs()."""
    workspace = workspace.resolve()
    cur = workspace.parent
    for _ in range(_ANCESTOR_SEARCH_DEPTH):
        candidate = cur / "CLAUDE.md"
        if candidate.is_file():
            return candidate
        if cur.parent == cur:
            break
        cur = cur.parent
    return None


def find_project_docs(workspace: Path) -> list[Path]:
    """CLAUDE.md and/or PROJECT.md directly at the workspace root."""
    out = []
    for name in ("CLAUDE.md", "PROJECT.md"):
        p = workspace / name
        if p.is_file():
            out.append(p)
    return out


def is_adequate(path: Path) -> bool:
    """Documented heuristic, not a quality judgment: exists and isn't just a
    stub/placeholder. Catches the obvious "near-empty file" case only."""
    try:
        return len(path.read_text(encoding="utf-8", errors="replace").strip()) >= _ADEQUATE_MIN_CHARS
    except OSError:
        return False


def _detect_stack(workspace: Path) -> list[str]:
    found = []
    for pattern, label in _MANIFEST_LANGUAGE_MAP.items():
        if (workspace / pattern).is_file():
            found.append(label)
    return found


def _top_level_structure(workspace: Path, max_entries: int = 25) -> list[str]:
    entries: list[str] = []
    try:
        for p in sorted(workspace.iterdir()):
            if p.name in _SKIP_DIRS or p.name.startswith("."):
                continue
            entries.append(p.name + ("/" if p.is_dir() else ""))
            if len(entries) >= max_entries:
                break
    except OSError:
        pass
    return entries


def generate_stewardship_doc(workspace: Path) -> str:
    """A REAL scan-derived doc, not a placeholder: detected stack + top-level
    structure + a clearly-marked provenance note (AI-generated, needs human
    review) + a Positions board for the multi-agent chat room to use."""
    stack = _detect_stack(workspace)
    structure = _top_level_structure(workspace)
    stack_block = ("- " + "\n- ".join(stack)) if stack else (
        "_No recognized manifest file found (package.json, pyproject.toml, "
        "Cargo.toml, go.mod, ...)._"
    )
    structure_block = "\n".join(structure) if structure else "(empty or unreadable workspace)"
    return (
        f"# {workspace.name}\n\n"
        "> Auto-generated by Determinex's stewardship scan on first use -- this "
        "is a starting point, not a substitute for a human-reviewed project "
        "doc. Edit freely; a future scan will not overwrite an already-adequate "
        "file (see determinex_stewardship.is_adequate()).\n\n"
        "## Detected stack\n\n"
        f"{stack_block}\n\n"
        "## Top-level structure\n\n"
        f"```\n{structure_block}\n```\n"
    )


def resolve_stewardship_content(workspace: Path) -> str:
    """The single entry point session creation calls: return the best
    available stewardship content for `workspace`, generating and persisting
    a PROJECT.md if nothing adequate exists yet. The runtime doc (if found)
    is concatenated ABOVE the project doc -- it sets the conventions the
    project doc specializes, matching this project's own root-CLAUDE.md /
    Determinex/CLAUDE.md relationship."""
    parts: list[str] = []

    runtime_doc = find_runtime_doc(workspace)
    if runtime_doc and is_adequate(runtime_doc):
        parts.append(f"<!-- runtime doc: {runtime_doc} -->\n\n"
                     + runtime_doc.read_text(encoding="utf-8", errors="replace"))

    project_docs = [p for p in find_project_docs(workspace) if is_adequate(p)]
    if project_docs:
        for p in project_docs:
            parts.append(f"<!-- project doc: {p} -->\n\n"
                         + p.read_text(encoding="utf-8", errors="replace"))
    else:
        generated = generate_stewardship_doc(workspace)
        out_path = workspace / "PROJECT.md"
        try:
            out_path.write_text(generated, encoding="utf-8")
        except OSError:
            pass  # best-effort write; still return the content even if the write failed
        parts.append(f"<!-- generated stewardship doc: {out_path} -->\n\n{generated}")

    return "\n\n---\n\n".join(parts)


def resolve_stewardship_reference(workspace: Path) -> str:
    """Like resolve_stewardship_content, but returns a short POINTER to each
    discovered doc's file path instead of concatenating full file content.

    Every multi-agent chat-room turn embeds this reference (not the doc
    bodies) in its prompt -- found live 2026-07-22: seed_plan_from_stewardship
    embedded the FULL text of the root runtime CLAUDE.md + the workspace's own
    CLAUDE.md (this project's own is many thousands of words: autonomy
    policy, model routing tables, full ProgramBench history, ...), and every
    "Resync" appended ANOTHER full copy on top with no trimming. That whole,
    ever-growing blob got sent raw on EVERY turn to EVERY participant,
    overwhelming codex's context window until it gave up and started echoing
    fragments of the doc back instead of doing anything useful. Ryan, live:
    "our mission plan is too much upfront, we need to have it linked like a
    md." Full instructions still exist on disk -- claude-code already
    auto-discovers CLAUDE.md itself; codex/gemini-cli get pointed at the
    exact path and can read it with their own file tools if they need the
    detail, same as a human collaborator would open the file rather than
    have it pasted into every message.
    """
    paths: list[str] = []

    runtime_doc = find_runtime_doc(workspace)
    if runtime_doc and is_adequate(runtime_doc):
        paths.append(str(runtime_doc))

    project_docs = [p for p in find_project_docs(workspace) if is_adequate(p)]
    if project_docs:
        paths.extend(str(p) for p in project_docs)
    else:
        generated = generate_stewardship_doc(workspace)
        out_path = workspace / "PROJECT.md"
        try:
            out_path.write_text(generated, encoding="utf-8")
        except OSError:
            pass  # best-effort write; the path is still a valid reference
        paths.append(str(out_path))

    lines = [
        "Project instructions live in the file(s) below -- read them directly "
        "with your own file-read tool if you need the detail. Do not assume "
        "their content without reading; do not paste their content back "
        "verbatim in your response.",
    ]
    lines += [f"- {p}" for p in paths]
    return "\n".join(lines)


def main() -> int:
    import argparse
    import json

    parser = argparse.ArgumentParser(description="Determinex project stewardship doc discovery/generation")
    sub = parser.add_subparsers(dest="cmd")

    p_resolve = sub.add_parser("resolve")
    p_resolve.add_argument("workspace")

    p_generate = sub.add_parser("generate")
    p_generate.add_argument("workspace")

    args = parser.parse_args()

    if args.cmd == "resolve":
        content = resolve_stewardship_content(Path(args.workspace))
        print(json.dumps({"content": content}))
        return 0

    if args.cmd == "generate":
        print(json.dumps({"content": generate_stewardship_doc(Path(args.workspace))}))
        return 0

    parser.print_help()
    return 1


if __name__ == "__main__":
    sys.exit(main())
