"""Determinex Data Engineer: DataHub context-aware code generator.

Generates dbt SQL models and Airflow DAGs from schema read out of DataHub, so the
column list in the generated code is the catalog's, not a guess.

Two things this deliberately does NOT do, both learned from auditing the first
version:

  * It does not invent schema when the catalog is unreachable. The client raises
    `DataHubUnavailable`; this reports that and exits non-zero. The previous
    version silently fell back to fixtures and printed "[OK] Fetched 5 fields",
    so a failed run was indistinguishable from a real one -- in a tool whose
    entire claim is zero hallucination.

  * It does not reference a column it has not seen. The previous version emitted
    `where o.status != 'CANCELLED'` unconditionally; `status` only exists in the
    fixture, so against a real schema without it the "schema-verified" output was
    invalid SQL. Predicates are now emitted only when the column is present.

Generated artifacts are stamped with the provenance they were actually built
from, so a fixture-derived file can never be mistaken for a catalog-derived one.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.determinex_datahub import (  # noqa: E402
    LIVE,
    DataHubContextClient,
    DataHubUnavailable,
    DatasetSchema,
)


def _quote_cols(alias: str, names: list[str]) -> str:
    return ",\n    ".join(f"{alias}.{n}" for n in names)


def generate_dbt_model(orders: DatasetSchema, customers: DatasetSchema) -> str:
    """Build a dbt model from the columns the catalog actually reports."""
    order_names = orders.field_names()
    # Join key must exist on both sides or the model cannot be built at all.
    join_key = "customer_id"
    if not orders.has_field(join_key) or not customers.has_field(join_key):
        raise ValueError(
            f"cannot join {orders.name} to {customers.name}: "
            f"both need a '{join_key}' column (orders has {order_names}, "
            f"customers has {customers.field_names()})"
        )

    cust_names = [n for n in customers.field_names() if n != join_key]

    # Only filter on a column the catalog reports. Hard-coding this predicate is
    # what made the previous output invalid against any schema lacking `status`.
    where_clause = ""
    if orders.has_field("status"):
        where_clause = "\nwhere o.status != 'CANCELLED'"

    provenance_note = (
        "-- Schema source: DataHub live catalog"
        if orders.is_live and customers.is_live
        else "-- Schema source: OFFLINE FIXTURES -- not verified against a live catalog"
    )

    return f"""-- Auto-generated by Determinex Autonomous Data Engineer
{provenance_note}
-- Upstream: {orders.urn}
--           {customers.urn}

with orders as (
    select * from {{{{ ref('stg_orders') }}}}
),
customers as (
    select * from {{{{ ref('stg_customers') }}}}
)

select
    {_quote_cols("o", order_names)},
    {_quote_cols("c", cust_names)}
from orders o
left join customers c on o.{join_key} = c.{join_key}{where_clause}
""".strip()


def generate_airflow_dag(dag_id: str, dbt_model_name: str, provenance: str) -> str:
    note = (
        "# Schema source: DataHub live catalog"
        if provenance == LIVE
        else "# Schema source: OFFLINE FIXTURES -- not verified against a live catalog"
    )
    return f"""# Auto-generated by Determinex Autonomous Data Engineer
{note}

from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.bash import BashOperator

default_args = {{
    'owner': 'determinex_agent',
    'depends_on_past': False,
    'start_date': datetime(2026, 1, 1),
    'email_on_failure': False,
    'retries': 2,
    'retry_delay': timedelta(minutes=5),
}}

with DAG(
    '{dag_id}',
    default_args=default_args,
    description='DataHub schema-verified dbt execution pipeline',
    schedule_interval='@daily',
    catchup=False,
    tags=['datahub', 'determinex', 'dbt'],
) as dag:

    run_dbt_model = BashOperator(
        task_id='run_dbt_{dbt_model_name}',
        bash_command='dbt run --select {dbt_model_name}',
    )

    test_dbt_model = BashOperator(
        task_id='test_dbt_{dbt_model_name}',
        bash_command='dbt test --select {dbt_model_name}',
    )

    run_dbt_model >> test_dbt_model
""".strip()


def main() -> int:
    ap = argparse.ArgumentParser(description="Determinex DataHub Autonomous Data Engineer")
    ap.add_argument(
        "--mock-run",
        action="store_true",
        help="Use offline fixtures instead of a live DataHub. Output is stamped as unverified.",
    )
    ap.add_argument("--out-dir", default="examples/datahub", help="Where to write artifacts")
    ap.add_argument("--emit-lineage", action="store_true", help="Write lineage back to DataHub")
    args = ap.parse_args()

    client = DataHubContextClient(mock_mode=args.mock_run)
    orders_urn = "urn:li:dataset:(urn:li:dataPlatform:snowflake,analytics.orders,PROD)"
    customers_urn = "urn:li:dataset:(urn:li:dataPlatform:snowflake,analytics.customers,PROD)"

    src = "offline fixtures" if args.mock_run else f"DataHub at {client.gql_url}"
    print(f"[INFO] Reading schema from {src} ...")

    try:
        orders = client.get_dataset_schema(orders_urn)
        customers = client.get_dataset_schema(customers_urn)
    except DataHubUnavailable as exc:
        # Deliberately fatal. Falling back to fixtures here is the bug this
        # integration is supposed to be a counterexample to.
        print(f"[FAIL] {exc}", file=sys.stderr)
        print("[FAIL] Refusing to generate code against an unverified schema.", file=sys.stderr)
        print("       Re-run with --mock-run to use offline fixtures on purpose.", file=sys.stderr)
        return 2

    print(f"  [{orders.provenance.upper()}] {orders.name}: {len(orders.fields)} fields")
    print(f"  [{customers.provenance.upper()}] {customers.name}: {len(customers.fields)} fields")

    try:
        dbt_sql = generate_dbt_model(orders, customers)
    except ValueError as exc:
        print(f"[FAIL] {exc}", file=sys.stderr)
        return 3

    dag_code = generate_airflow_dag(
        "determinex_orders_enrichment_dag", "orders_enriched", orders.provenance
    )

    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    dbt_file = out / "sample_dbt_model.sql"
    dag_file = out / "sample_airflow_dag.py"
    dbt_file.write_text(dbt_sql + "\n", encoding="utf-8")
    dag_file.write_text(dag_code + "\n", encoding="utf-8")

    print("\n[DONE] Wrote:")
    print(f"  - {dbt_file}")
    print(f"  - {dag_file}")

    if args.emit_lineage:
        ok = client.emit_lineage(
            "urn:li:dataset:(urn:li:dataPlatform:snowflake,analytics.orders_enriched,PROD)",
            [orders_urn, customers_urn],
        )
        # emit_lineage returns False in mock mode by design: there is nothing to
        # write to, and claiming success would be the same lie the old
        # `return True` told.
        print(f"[LINEAGE] emitted={ok}" + ("" if ok else "  (no live DataHub to write to)"))

    if not orders.is_live:
        print(
            "\n[NOTE] Built from offline fixtures. The artifacts are stamped as "
            "unverified and must not be presented as catalog-verified output."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
