"""
pb_candidate_score.py — Score top CLI tool candidates via GitHub API.

For the top N new candidates (by extraction frequency), fetches GitHub
metadata and computes a candidate_score. Writes tbsk_scored.json and
prints a ranked table.

Usage:
  python scripts/pb_candidate_score.py
  python scripts/pb_candidate_score.py --input corpus/candidates/master_candidates.json
  python scripts/pb_candidate_score.py --top 30 --dry-run

Requires: GITHUB_TOKEN env var (optional but avoids rate limits)

# Generated by Determinex integration pipeline
# Source: https://github.com/trimstray/the-book-of-secret-knowledge
# Date: 2026-06-07
# Do not edit manually — re-run pb_candidate_score.py to regenerate
"""
from __future__ import annotations

import argparse
import json
import math
import os
import time
import urllib.request
import urllib.error
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).parent.parent
CANDIDATES_DIR = ROOT / "corpus" / "candidates"

DETERMINEX_LANGUAGES = {"rust", "go", "c", "c++"}


def github_get(path: str) -> dict | None:
    url = f"https://api.github.com/{path.lstrip('/')}"
    req = urllib.request.Request(url)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        if e.code == 403:
            print(f"  Rate limited on {path}, sleeping 60s...")
            time.sleep(60)
        elif e.code == 404:
            return None
        else:
            print(f"  HTTP {e.code} for {path}")
        return None
    except Exception as e:
        print(f"  Error fetching {path}: {e}")
        return None


def compute_score(meta: dict) -> float:
    stars = meta.get("stargazers_count", 0) or 0
    lang = (meta.get("language") or "").lower()
    updated_at = meta.get("updated_at") or ""
    open_issues = meta.get("open_issues_count", 0) or 0
    has_releases = bool(meta.get("has_releases"))

    score = math.log10(stars + 1) * 3
    if lang in DETERMINEX_LANGUAGES:
        score += 2
    elif lang:
        score += 1

    if updated_at:
        try:
            updated = datetime.fromisoformat(updated_at.replace("Z", "+00:00"))
            age_days = (datetime.now(timezone.utc) - updated).days
            if age_days < 730:
                score += 1
        except Exception:
            pass

    if has_releases:
        score += 1

    if open_issues > 500:
        score -= 1

    return round(score, 2)


def score_candidates(candidates: list[dict], top_n: int, dry_run: bool) -> list[dict]:
    # Filter to new candidates only, sort by frequency desc
    new_only = [c for c in candidates if c.get("pb200_status") == "NOT_IN_PB200"]
    new_only.sort(key=lambda c: c.get("frequency", 1), reverse=True)
    to_score = new_only[:top_n]

    print(f"\nScoring top {len(to_score)} candidates via GitHub API...")

    scored = []
    for i, c in enumerate(to_score):
        owner, repo = c["owner"], c["repo"]
        print(f"  [{i+1}/{len(to_score)}] {owner}/{repo}...", end=" ", flush=True)

        if dry_run:
            print("(dry-run)")
            c["stars"] = 0
            c["language"] = None
            c["candidate_score"] = 0.0
            scored.append(c)
            continue

        meta = github_get(f"repos/{owner}/{repo}") or {}

        # Check for releases
        releases = github_get(f"repos/{owner}/{repo}/releases?per_page=1")
        meta["has_releases"] = bool(releases)

        stars = meta.get("stargazers_count", 0)
        lang = meta.get("language") or ""
        score = compute_score(meta)

        c["stars"] = stars
        c["language"] = lang
        c["candidate_score"] = score
        c["updated_at"] = meta.get("updated_at")
        print(f"*{stars} {lang} score={score}")
        scored.append(c)

        # Gentle rate limiting
        time.sleep(0.5)

    scored.sort(key=lambda c: c.get("candidate_score") or 0, reverse=True)
    return scored


def print_table(scored: list[dict], top_n: int = 20) -> None:
    rows = scored[:top_n]
    print(f"\n{'-'*90}")
    print(f"{'Tool':<24} {'Language':<10} {'Stars':>6} {'Score':>6}  Description")
    print(f"{'-'*90}")
    for c in rows:
        name = c["name"][:23]
        lang = (c["language"] or "?")[:9]
        stars = c.get("stars") or 0
        star_str = f"{stars/1000:.0f}k" if stars >= 1000 else str(stars)
        score = c.get("candidate_score") or 0
        desc = (c.get("description") or "")[:45]
        print(f"{name:<24} {lang:<10} {star_str:>6} {score:>6.1f}  {desc}")
    print(f"{'-'*90}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Score CLI tool candidates via GitHub API")
    parser.add_argument("--input", type=Path, help="Input candidates JSON (default: tbsk_candidates.json)")
    parser.add_argument("--output", type=Path, help="Output scored JSON path")
    parser.add_argument("--top", type=int, default=50, help="Number of candidates to score (default: 50)")
    parser.add_argument("--print-top", type=int, default=20, help="Rows to print in table (default: 20)")
    parser.add_argument("--dry-run", action="store_true", help="Skip GitHub API calls")
    args = parser.parse_args()

    source = args.input or (CANDIDATES_DIR / "tbsk_candidates.json")
    if not source.exists():
        print(f"ERROR: {source} not found — run pb_candidate_mine.py first")
        return

    data = json.loads(source.read_text())
    candidates = data.get("candidates", [])
    print(f"Loaded {len(candidates)} candidates from {source.name}")

    scored = score_candidates(candidates, top_n=args.top, dry_run=args.dry_run)

    # Update the candidates list with scores
    scored_urls = {c["github_url"].lower(): c for c in scored}
    for c in candidates:
        key = c["github_url"].lower()
        if key in scored_urls:
            c.update(scored_urls[key])

    result = {
        "extracted_at": datetime.now(timezone.utc).isoformat(),
        "source": data.get("source", source.name),
        "total_extracted": data.get("total_extracted", len(candidates)),
        "already_in_pb200": data.get("already_in_pb200", 0),
        "new_candidates": data.get("new_candidates", 0),
        "scored_top_n": len(scored),
        "candidates": candidates,
    }

    out = args.output or source.parent / (source.stem.replace("_candidates", "") + "_scored.json")
    out.write_text(json.dumps(result, indent=2))
    print(f"\nWritten: {out}")

    print_table(scored, top_n=args.print_top)

    top = scored[0] if scored else {}
    print(f"\nTop candidate: {top.get('name', '?')} "
          f"({top.get('stars', 0)} stars, {top.get('language', '?')}, "
          f"score {top.get('candidate_score', 0)})")


if __name__ == "__main__":
    main()
