"""
pb_candidate_mine.py — Mine CLI tool candidates from external sources.

Parses The Book of Secret Knowledge (Markdown) and HTML sources,
extracts GitHub-linked CLI tools, cross-references against PB200 board,
and writes corpus/candidates/tbsk_candidates.json.

Usage:
  python scripts/pb_candidate_mine.py
  python scripts/pb_candidate_mine.py --source corpus/candidates/linuxlinks_raw.html
  python scripts/pb_candidate_mine.py --merge --output corpus/candidates/master_candidates.json
  python scripts/pb_candidate_mine.py --dry-run

# Generated by Determinex integration pipeline
# Source: https://github.com/trimstray/the-book-of-secret-knowledge
# Date: 2026-06-07
# Do not edit manually — re-run pb_candidate_mine.py to regenerate
"""

from __future__ import annotations

import argparse
import json
import re
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).parent.parent
CANDIDATES_DIR = ROOT / "corpus" / "candidates"
INDEX_FILE = ROOT / "corpus" / "programbench" / "eval_index.json"

CLI_KEYWORDS = {
    "cli",
    "command-line",
    "command line",
    "terminal",
    "shell",
    "tui",
    "ncurses",
    "console",
    "binary",
    "executable",
    "tool",
    "utility",
    "grep",
    "find",
    "search",
    "replace",
    "convert",
    "parse",
    "format",
    "lint",
    "check",
    "watch",
    "run",
    "build",
    "compile",
    "generate",
    "encode",
    "decode",
    "compress",
    "diff",
    "sort",
    "filter",
    "transform",
    "monitor",
    "log",
    "pipe",
    "stdin",
    "stdout",
    "unix",
    "posix",
}


def load_eval_index() -> list[dict]:
    if INDEX_FILE.exists():
        return json.loads(INDEX_FILE.read_text(encoding="utf-8"))
    return []


def build_pb_lookup(index: list[dict]) -> set[str]:
    """Build a set of slugs/repo-names for fast membership check."""
    slugs: set[str] = set()
    for e in index:
        slugs.add(e["slug"].lower())
        slugs.add(e["slug"].lower().replace("-", ""))
        slugs.add(e["slug"].lower().replace("_", "-"))
    return slugs


def is_cli_tool(desc: str) -> bool:
    desc_lower = desc.lower()
    return any(kw in desc_lower for kw in CLI_KEYWORDS)


def classify_pb_status(name: str, owner: str, repo: str, pb_slugs: set[str]) -> str:
    checks = [
        name.lower(),
        repo.lower(),
        name.lower().replace("-", ""),
        repo.lower().replace("-", ""),
        f"{owner}__{repo}".lower(),
    ]
    for c in checks:
        if c in pb_slugs:
            return "IN_PB200"
    # Fuzzy: check if any PB slug contains the repo name as a substring
    for slug in pb_slugs:
        if repo.lower() in slug or slug in repo.lower():
            if len(repo) > 3:
                return "POSSIBLE_MATCH"
    return "NOT_IN_PB200"


# ──────────────────────────────────────────────────────────────────
# MARKDOWN PARSER (TBSK)
# ──────────────────────────────────────────────────────────────────

# Standard markdown links: [name](https://github.com/owner/repo)
GITHUB_MD_PATTERN = re.compile(
    r"\[([^\]]+)\]\(https://github\.com/([^/\)]+)/([^/\)#\s]+)[^\)]*\)",
    re.IGNORECASE,
)

# HTML anchor tags in markdown (TBSK uses these): <a href="https://github.com/owner/repo"><b>name</b></a> - desc
GITHUB_HTML_ANCHOR = re.compile(
    r'<a\s+href=["\']https://github\.com/([^/"\'\s]+)/([^/"\'\s#?]+)[^"\']*["\']>'
    r"(?:<[^>]+>)?([^<]+)(?:</[^>]+>)?</a>\s*[-–—]\s*([^\n<]{0,200})",
    re.IGNORECASE,
)

# Also bare HTML anchors without description
GITHUB_HTML_ANCHOR_BARE = re.compile(
    r'<a\s+href=["\']https://github\.com/([^/"\'\s]+)/([^/"\'\s#?]+)[^"\']*["\']>'
    r"(?:<[^>]+>)?([^<]+)",
    re.IGNORECASE,
)


def mine_markdown(path: Path) -> list[dict]:
    text = path.read_text(encoding="utf-8", errors="replace")
    seen: dict[str, dict] = {}

    # Try HTML anchor with description first (TBSK format)
    for m in GITHUB_HTML_ANCHOR.finditer(text):
        owner = m.group(1).strip()
        repo = m.group(2).strip()
        name = m.group(3).strip()
        desc = m.group(4).strip()
        url = f"https://github.com/{owner}/{repo}"
        key = url.lower()
        if key in seen:
            seen[key]["_freq"] += 1
        else:
            seen[key] = {
                "name": name,
                "github_url": url,
                "owner": owner,
                "repo": repo,
                "description": desc,
                "_freq": 1,
                "_source": path.name,
            }

    # Standard markdown links
    for m in GITHUB_MD_PATTERN.finditer(text):
        name = m.group(1).strip()
        owner = m.group(2).strip()
        repo = m.group(3).strip().rstrip(")")
        url = f"https://github.com/{owner}/{repo}"
        key = url.lower()
        if key not in seen:
            # Try to find description on same line
            pos = m.end()
            line_rest = text[pos : pos + 200].split("\n")[0]
            desc_m = re.match(r"\s*[-–—]\s*(.+)", line_rest)
            desc = desc_m.group(1).strip() if desc_m else ""
            seen[key] = {
                "name": name,
                "github_url": url,
                "owner": owner,
                "repo": repo,
                "description": desc,
                "_freq": 1,
                "_source": path.name,
            }

    # Bare HTML anchors (fallback, lower priority)
    for m in GITHUB_HTML_ANCHOR_BARE.finditer(text):
        owner = m.group(1).strip()
        repo = m.group(2).strip()
        name = m.group(3).strip()
        url = f"https://github.com/{owner}/{repo}"
        key = url.lower()
        if key not in seen:
            seen[key] = {
                "name": name,
                "github_url": url,
                "owner": owner,
                "repo": repo,
                "description": "",
                "_freq": 1,
                "_source": path.name,
            }

    return list(seen.values())


# ──────────────────────────────────────────────────────────────────
# HTML PARSER (linuxlinks, awesome-docker)
# ──────────────────────────────────────────────────────────────────

GITHUB_HTML_PATTERN = re.compile(
    r'href=["\']https://github\.com/([^/"\'\s]+)/([^/"\'\s#]+)[^"\']*["\'][^>]*>([^<]+)<',
    re.IGNORECASE,
)


def mine_html(path: Path) -> list[dict]:
    try:
        from bs4 import BeautifulSoup

        soup = BeautifulSoup(path.read_bytes(), "html.parser")
        seen: dict[str, dict] = {}
        for a in soup.find_all("a", href=True):
            href = a["href"]
            m = re.match(r"https://github\.com/([^/]+)/([^/\s#?]+)", href)
            if not m:
                continue
            owner, repo = m.group(1), m.group(2)
            name = a.get_text(strip=True) or repo
            # Try to get description from parent element text
            parent = a.parent
            desc = parent.get_text(separator=" ", strip=True) if parent else ""
            desc = desc[:200]
            url = f"https://github.com/{owner}/{repo}"
            key = url.lower()
            if key in seen:
                seen[key]["_freq"] += 1
                continue
            seen[key] = {
                "name": name,
                "github_url": url,
                "owner": owner,
                "repo": repo,
                "description": desc,
                "_freq": 1,
                "_source": path.name,
            }
        return list(seen.values())
    except ImportError:
        # Fall back to regex
        text = path.read_text(encoding="utf-8", errors="replace")
        seen = {}
        for m in GITHUB_HTML_PATTERN.finditer(text):
            owner, repo, name = m.group(1), m.group(2), m.group(3).strip()
            url = f"https://github.com/{owner}/{repo}"
            key = url.lower()
            if key not in seen:
                seen[key] = {
                    "name": name,
                    "github_url": url,
                    "owner": owner,
                    "repo": repo,
                    "description": "",
                    "_freq": 1,
                    "_source": path.name,
                }
        return list(seen.values())


def mine_source(path: Path) -> list[dict]:
    suffix = path.suffix.lower()
    if suffix in (".md", ".txt", ".rst"):
        return mine_markdown(path)
    return mine_html(path)


# ──────────────────────────────────────────────────────────────────
# MAIN PIPELINE
# ──────────────────────────────────────────────────────────────────


def mine_and_save(source_path: Path, output_path: Path, dry_run: bool = False) -> list[dict]:
    index = load_eval_index()
    pb_slugs = build_pb_lookup(index)

    raw = mine_source(source_path)

    # Filter to CLI tools and annotate
    candidates = []
    for r in raw:
        desc = r["description"] or r["repo"]
        if not is_cli_tool(desc):
            continue
        status = classify_pb_status(r["name"], r["owner"], r["repo"], pb_slugs)
        candidates.append(
            {
                "name": r["name"],
                "github_url": r["github_url"],
                "owner": r["owner"],
                "repo": r["repo"],
                "description": r["description"],
                "pb200_status": status,
                "frequency": r["_freq"],
                "source": r["_source"],
                "language": None,
                "stars": None,
                "candidate_score": None,
            }
        )

    already = sum(1 for c in candidates if c["pb200_status"] == "IN_PB200")
    new_cands = [c for c in candidates if c["pb200_status"] == "NOT_IN_PB200"]
    possible = sum(1 for c in candidates if c["pb200_status"] == "POSSIBLE_MATCH")

    result = {
        "extracted_at": datetime.now(UTC).isoformat(),
        "source": source_path.name,
        "total_extracted": len(candidates),
        "already_in_pb200": already,
        "possible_match": possible,
        "new_candidates": len(new_cands),
        "candidates": candidates,
    }

    print(f"  Source: {source_path.name}")
    print(f"  Extracted: {len(candidates)} CLI tools")
    print(f"  IN_PB200: {already}  POSSIBLE: {possible}  NEW: {len(new_cands)}")

    if not dry_run:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(json.dumps(result, indent=2))
        print(f"  Written: {output_path}")

    return candidates


def merge_sources(source_files: list[Path], output_path: Path, dry_run: bool = False) -> None:
    """Merge multiple candidate files into master_candidates.json."""
    merged: dict[str, dict] = {}
    for sf in source_files:
        if not sf.exists():
            print(f"  SKIP (not found): {sf}")
            continue
        data = json.loads(sf.read_text())
        for c in data.get("candidates", []):
            key = c["github_url"].lower()
            if key in merged:
                # Boost score for multi-source presence
                merged[key]["frequency"] = merged[key].get("frequency", 1) + 1
                existing_sources = merged[key].get("sources", [merged[key].get("source", "")])
                if c["source"] not in existing_sources:
                    existing_sources.append(c["source"])
                merged[key]["sources"] = existing_sources
            else:
                c["sources"] = [c.get("source", "")]
                merged[key] = c

    candidates = list(merged.values())
    new_only = [c for c in candidates if c["pb200_status"] == "NOT_IN_PB200"]

    result = {
        "extracted_at": datetime.now(UTC).isoformat(),
        "source": "merged",
        "source_files": [str(sf) for sf in source_files],
        "total_unique": len(candidates),
        "new_candidates": len(new_only),
        "candidates": sorted(candidates, key=lambda c: c.get("frequency", 1), reverse=True),
    }

    print(f"\nMaster candidate list: {len(new_only)} tools not yet in PB200")

    if not dry_run:
        output_path.write_text(json.dumps(result, indent=2))
        print(f"Written: {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Mine CLI tool candidates from external sources")
    parser.add_argument("--source", type=Path, help="Source file to mine (default: tbsk_raw.md)")
    parser.add_argument("--output", type=Path, help="Output JSON path")
    parser.add_argument(
        "--merge", action="store_true", help="Merge all candidate files into master"
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Print what would be done, no writes"
    )
    args = parser.parse_args()

    if args.merge:
        sources = [
            CANDIDATES_DIR / "tbsk_candidates.json",
            CANDIDATES_DIR / "stackshare_candidates.json",
            CANDIDATES_DIR / "linuxlinks_candidates.json",
            CANDIDATES_DIR / "awesome_docker_candidates.json",
        ]
        out = args.output or CANDIDATES_DIR / "master_candidates.json"
        merge_sources(sources, out, dry_run=args.dry_run)
        return

    source = args.source or (CANDIDATES_DIR / "tbsk_raw.md")
    if not source.exists():
        print(f"ERROR: source not found: {source}")
        return

    # Determine output name from source
    stem = source.stem.replace("_raw", "")
    out = args.output or (CANDIDATES_DIR / f"{stem}_candidates.json")
    mine_and_save(source, out, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
