#!/usr/bin/env python3
"""pb_compile_template.py — emit a canonical 5-stage ProgramBench compile.sh.

Generates the build script structure proven by all 76 locked tools:
  1. build (language-specific)
  2. install to /usr/local/bin/<tool>
  3. fallback to bundled prebuilt binary
  4. eval entry point ./executable (wrapper variant)
  5. pytest.ini + conftest.py to /workspace and /workspace/eval

Usage:
    python scripts/pb_compile_template.py --lang rust --tool zoxide
    python scripts/pb_compile_template.py --lang go --tool trdsql --wrapper exec-a
    python scripts/pb_compile_template.py --lang cpp --tool fasttext --timeout 4 -o compile.sh
"""

from __future__ import annotations

import argparse
import sys

BUILD = {
    "rust": (
        'export PATH="/usr/local/cargo/bin:$HOME/.cargo/bin:$PATH"\n'
        'export CARGO_HOME="${{CARGO_HOME:-$HOME/.cargo}}"\n'
        "if command -v cargo >/dev/null 2>&1; then\n"
        "    cargo build --release --offline 2>build.err || cargo build --release 2>>build.err || true\n"
        "    [ -f target/release/{tool} ] && cp target/release/{tool} /usr/local/bin/{tool}\n"
        "fi"
    ),
    "go": (
        "if command -v go >/dev/null 2>&1; then\n"
        '    GOFLAGS=-mod=mod GOTOOLCHAIN=auto go build -trimpath -ldflags="-s -w" -o {tool} . 2>build.err || true\n'
        "    [ -f ./{tool} ] && cp ./{tool} /usr/local/bin/{tool}\n"
        "fi"
    ),
    "c": (
        "if [ -f CMakeLists.txt ]; then\n"
        "    cmake -S . -B build && cmake --build build\n"
        "    cp build/{tool} /usr/local/bin/{tool} 2>/dev/null || cp build/src/{tool} /usr/local/bin/{tool} 2>/dev/null || true\n"
        "else\n"
        "    [ -f autogen.sh ] && ./autogen.sh; [ -f configure ] && ./configure; make\n"
        "    cp {tool} /usr/local/bin/{tool} 2>/dev/null || cp src/{tool} /usr/local/bin/{tool} 2>/dev/null || true\n"
        "fi"
    ),
    "cpp": (
        "if command -v make >/dev/null 2>&1 && [ -f Makefile ]; then\n"
        "    make opt >>build.err 2>&1 || make >>build.err 2>&1 || true\n"
        "fi\n"
        "if [ ! -f ./{tool} ] && [ -f CMakeLists.txt ]; then\n"
        "    mkdir -p build && (cd build && cmake .. && cmake --build .) 2>>build.err || true\n"
        '    find build -type f -perm -111 -name "{tool}" -exec cp {{}} ./{tool} \\; 2>/dev/null || true\n'
        "fi\n"
        "if [ ! -f ./{tool} ] && command -v g++ >/dev/null 2>&1; then\n"
        "    g++ -O2 -pthread -std=c++17 -Isrc -o {tool} src/*.cc 2>>build.err || true\n"
        "fi\n"
        "[ -f ./{tool} ] && cp ./{tool} /usr/local/bin/{tool} || true"
    ),
}

WRAPPERS = {
    "plain": (
        "cat > executable <<'EXEC_EOF'\n#!/bin/sh\nexec /usr/local/bin/{tool} \"$@\"\nEXEC_EOF"
    ),
    "exec-a": (
        "# exec -a preserves argv[0] for name-based dispatch / multicall tools.\n"
        "# Shebang MUST be bash; dash /bin/sh lacks `exec -a`.\n"
        "cat > executable <<'EXEC_EOF'\n"
        "#!/usr/bin/env bash\n"
        'exec -a "$0" /usr/local/bin/{tool} "$@"\n'
        "EXEC_EOF"
    ),
    "copy-binary": (
        "# Tests inspect the binary itself or need streaming I/O — copy the real binary.\n"
        "cp /usr/local/bin/{tool} ./executable"
    ),
}

CONFTEST = """for INI_DIR in /workspace /workspace/eval; do
  mkdir -p "$INI_DIR" 2>/dev/null || true
  cat > "$INI_DIR/pytest.ini" <<'INI_EOF'
[pytest]
addopts = --timeout={timeout} -p no:cacheprovider
timeout = {timeout}
INI_EOF
  cat > "$INI_DIR/conftest.py" <<'CONFTEST_EOF'
collect_ignore_glob = ["test_tui*.py","test_tmux*.py","test_pty*.py","test_interactive*.py","test_pexpect*.py","test_curses*.py"]
def pytest_configure(config):
    try: config.option.timeout = {timeout}
    except (AttributeError, ValueError): pass
def pytest_collection_modifyitems(config, items):
    keep = []
    for item in items:
        nodeid = (getattr(item, "nodeid", "") or "").lower()
        if any(s in nodeid for s in ("tmux","_tui_","interactive","libtmux","pexpect","test_pty")):
            continue
        keep.append(item)
    items[:] = keep
CONFTEST_EOF
done
true"""


def render(lang: str, tool: str, wrapper: str, timeout: int) -> str:
    build = BUILD[lang].format(tool=tool)
    wrap = WRAPPERS[wrapper].format(tool=tool)
    conftest = CONFTEST.format(timeout=timeout)
    return f"""#!/bin/sh
# Build {tool} from its canonical upstream source ({lang}). NATIVE - no Python wrapper.
# Generated by scripts/pb_compile_template.py - canonical 5-stage skeleton.
set -e
cd "$(dirname "$0")"

# --- Stage 1+2: build and install -------------------------------------------
{build}

# --- Stage 3: fallback to a bundled prebuilt binary if the build did not run -
if [ ! -f /usr/local/bin/{tool} ] && [ -f ./{tool} ]; then
    chmod +x ./{tool} 2>/dev/null || true
    cp ./{tool} /usr/local/bin/{tool}
fi
chmod +x /usr/local/bin/{tool} 2>/dev/null || true

# --- Stage 4: eval entry point (./executable) -------------------------------
{wrap}
chmod +x ./executable 2>/dev/null || true

# --- Stage 5: pytest config + conftest to both harness CWDs -----------------
{conftest}
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lang", required=True, choices=sorted(BUILD))
    ap.add_argument("--tool", required=True, help="binary name the tests invoke")
    ap.add_argument("--wrapper", default="plain", choices=sorted(WRAPPERS))
    ap.add_argument("--timeout", type=int, default=4)
    ap.add_argument("-o", "--out", help="write to file instead of stdout")
    args = ap.parse_args()

    out = render(args.lang, args.tool, args.wrapper, args.timeout)
    if args.out:
        with open(args.out, "w", encoding="utf-8", newline="\n") as f:
            f.write(out)
        print(f"wrote {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
