"""Generate `frontend/src-tauri/permissions/app-commands.toml` from `generate_handler!`.

WHY THIS IS A REPO SCRIPT
-------------------------
The permission file was first generated by a script living in a session scratchpad, and its own
header said "Regenerate after changing generate_handler!: python <scratchpad>/gen_acl.py" -- a
path that does not survive the session. So the one maintenance step the file documents was
unperformable by anyone else, which matters because a *missing* permission is not a build error:
Tauri denies that command at runtime and the feature silently stops working.

That is not hypothetical. Adding `set_project_root` to `generate_handler!` (the .env project
boundary fix) left the permission behind, and `tests/test_tauri_acl.py` caught it. This script is
the other half of that guard -- the test says what drifted, this fixes it.

    python scripts/dev/gen_tauri_acl.py            # rewrite the file
    python scripts/dev/gen_tauri_acl.py --check    # exit 1 if it would change

Writes only the one file, derived from lib.rs. The command set is parsed exactly the way
tests/test_tauri_acl.py parses it, deliberately: if the two disagreed, a green test would not mean
a correct file.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
TAURI = REPO_ROOT / "frontend" / "src-tauri"
LIB_RS = TAURI / "src" / "lib.rs"
OUT = TAURI / "permissions" / "app-commands.toml"

HEADER = """\
# Generated from the generate_handler! list in src/lib.rs.
#
# Its existence is the point: without a permissions/ directory Tauri sets
# has_app_acl_manifest = false and skips the ACL check for app commands entirely, so every
# command was reachable from any webview with no permission and no window restriction.
# Enabling the ACL makes the capability's `windows` list apply to app commands, and makes
# any command added later denied by default rather than silently exposed.
#
# Regenerate after changing generate_handler!:
#   python scripts/dev/gen_tauri_acl.py
# tests/test_tauri_acl.py fails if this drifts from the registered set.
"""


def registered_commands() -> list[str]:
    """Parsed identically to tests/test_tauri_acl.py::registered_commands."""
    src = LIB_RS.read_text(encoding="utf-8")
    match = re.search(r"generate_handler!\s*\[(.*?)\]", src, re.DOTALL)
    if not match:
        sys.exit(f"could not find generate_handler! in {LIB_RS}")
    body = re.sub(r"//.*?$", "", match.group(1), flags=re.MULTILINE)
    return sorted({c.strip().split("::")[-1] for c in body.split(",") if c.strip()})


def render(commands: list[str]) -> str:
    ident = {c: "allow-" + c.replace("_", "-") for c in commands}
    lines = [
        HEADER,
        "",
        "[[set]]",
        'identifier = "allow-app-commands"',
        'description = "Every command registered in generate_handler!."',
        "permissions = [",
    ]
    lines += [f'    "{ident[c]}",' for c in commands]
    lines.append("]")
    for c in commands:
        lines += [
            "",
            "[[permission]]",
            f'identifier = "{ident[c]}"',
            f'description = "Enables the {c} command."',
            "[permission.commands]",
            f'allow = ["{c}"]',
        ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the file is out of date instead of rewriting it",
    )
    args = ap.parse_args()

    commands = registered_commands()
    rendered = render(commands)
    current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""

    if rendered == current:
        print(f"up to date: {len(commands)} commands")
        return 0
    if args.check:
        print(
            f"OUT OF DATE: {OUT.relative_to(REPO_ROOT).as_posix()} "
            f"does not match generate_handler! ({len(commands)} commands). "
            f"Run: python scripts/dev/gen_tauri_acl.py"
        )
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO_ROOT).as_posix()} — {len(commands)} commands")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
