#!/usr/bin/env python3
"""
spec_to_pdf.py — render PROJECT_SPEC.md to the submission PDF, deterministically.

The AMD Track 2 rules require project documentation as a PDF. It had been produced by hand,
which meant every correction to the spec needed a manual regeneration, and twice the PDF that
existed was several fixes behind the markdown it claimed to render -- including one that still
carried duplicate section numbers and a promise of a section that did not exist.

A document generated by a repeatable command cannot drift from its source. That is the same
argument this project makes about oracles, applied to its own paperwork.

    python scripts/dev/spec_to_pdf.py --md <spec.md> --out <out.pdf>

Renders through the Playwright Chromium already vendored in frontend/node_modules, so it needs
no new dependency and no network.
"""

from __future__ import annotations

import argparse
import base64
import re
import subprocess
import sys
import tempfile
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent.parent

CSS = """
@page { size: A4; margin: 18mm 15mm 20mm 15mm; }
* { box-sizing: border-box; }
body {
  font-family: "Segoe UI", -apple-system, system-ui, sans-serif;
  font-size: 9.4pt; line-height: 1.52; color: #1a1d21; margin: 0;
  -webkit-font-smoothing: antialiased;
}
.cover {
  background: #0d1117; color: #fff; margin: -18mm -15mm 10mm -15mm;
  padding: 16mm 15mm 11mm 15mm;
}
.cover img { height: 42px; margin-bottom: 9mm; }
.cover h1 { font-size: 25pt; margin: 0 0 3mm 0; font-weight: 650; letter-spacing: -0.4pt; }
.cover .tag { color: #3ddc97; font-size: 10.5pt; margin: 0 0 6mm 0; font-weight: 500; }
.cover .meta { color: #8b949e; font-size: 7.6pt; line-height: 1.65; }
h2 {
  font-size: 14pt; font-weight: 640; margin: 9mm 0 3.5mm 0; padding-bottom: 1.8mm;
  border-bottom: 2px solid #0d9488; color: #0d1117; letter-spacing: -0.2pt;
  break-after: avoid;
}
h3 { font-size: 10.6pt; font-weight: 640; margin: 6mm 0 2.2mm 0; color: #0f172a; break-after: avoid; }
h4 { font-size: 9.6pt; font-weight: 640; margin: 5mm 0 2mm 0; color: #334155; break-after: avoid; }
p { margin: 0 0 2.6mm 0; orphans: 3; widows: 3; }
strong { font-weight: 640; color: #0d1117; }
a { color: #0d9488; text-decoration: none; }
code {
  font-family: "Cascadia Mono", Consolas, monospace; font-size: 8.1pt;
  background: #f1f5f9; padding: 0.6mm 1.1mm; border-radius: 2px; color: #0f172a;
}
pre {
  background: #f8fafc; border-left: 2.5px solid #0d9488; padding: 2.8mm 3.5mm;
  border-radius: 3px; overflow-x: auto; margin: 0 0 3mm 0; break-inside: avoid;
}
pre code { background: none; padding: 0; font-size: 7.9pt; line-height: 1.42; }
table {
  border-collapse: collapse; width: 100%; margin: 0 0 3.5mm 0;
  font-size: 8.5pt; break-inside: avoid;
}
th {
  background: #f1f5f9; text-align: left; padding: 1.8mm 2.4mm;
  border: 1px solid #e2e8f0; font-weight: 640; color: #0f172a;
}
td { padding: 1.8mm 2.4mm; border: 1px solid #e2e8f0; vertical-align: top; }
tbody tr:nth-child(even) { background: #fafbfc; }
blockquote {
  border-left: 2.5px solid #cbd5e1; background: #f8fafc; margin: 0 0 3mm 0;
  padding: 2.4mm 3.5mm; color: #334155; break-inside: avoid;
}
blockquote p:last-child { margin-bottom: 0; }
ul, ol { margin: 0 0 2.8mm 0; padding-left: 5.5mm; }
li { margin-bottom: 1.1mm; }
hr { border: 0; border-top: 1px solid #e2e8f0; margin: 7mm 0; }
em { color: #334155; }
.flow { margin: 0 0 4mm 0; break-inside: avoid; text-align: center; }
.flow .node {
  border: 1px solid #cbd5e1; border-radius: 4px; padding: 2mm 3mm;
  display: inline-block; min-width: 74mm; background: #fff;
}
.flow .node.gpu { background: #b91c3c; border-color: #b91c3c; color: #fff; }
.flow .node.oracle { background: #0d1117; border-color: #0d9488; color: #fff; }
.flow .node.plain { background: #f1f5f9; border-color: #e2e8f0; }
.flow .nh { font-weight: 640; font-size: 9pt; }
.flow .ns { font-size: 7.6pt; opacity: 0.85; margin-top: 0.6mm; }
.flow .arrow { color: #94a3b8; font-size: 10pt; line-height: 1.1; margin: 0.8mm 0; }
.flow .feedback {
  margin-top: 2.5mm; font-size: 7.6pt; color: #b91c3c;
  border-top: 1px dashed #fca5a5; padding-top: 1.8mm;
}
"""

FOOTER = (
    '<div style="font-size:7pt;color:#94a3b8;width:100%;padding:0 15mm;'
    'font-family:Segoe UI,sans-serif;display:flex;justify-content:space-between;">'
    "<span>Determinex &middot; Track 2 Project Specification &middot; AGPL-3.0-or-later</span>"
    '<span class="pageNumber"></span>/<span class="totalPages"></span></div>'
)


#: The architecture DAG, drawn in CSS. mermaid is not vendored in frontend/node_modules and
#: the renderer runs offline, so a ```mermaid fence shipped as raw diagram SOURCE in the PDF --
#: which is worse than no diagram, because it looks like a mistake rather than a decision.
_FLOW = [
    ("idea / spec", "", "plain"),
    ("C7 ARCHITECT", "7B Mistral &middot; decomposes into an ordered DAG", "box"),
    ("C1 BUILDER &mdash; the only GPU node",
     "1.5B Qwen2.5-Coder &middot; K candidates, varied temperature", "gpu"),
    ("ORACLE &mdash; deterministic, not a model",
     "rustc &middot; go build &middot; pytest &middot; tsc &middot; dotnet &middot; gcc<br>"
     "<i>the only node in the loop that decides anything</i>", "oracle"),
    ("commit to WAL, advance to the next step", "", "plain"),
    ("C3 MONITOR", "3B Llama-3.2 &middot; scores, may submit a rival approach", "box"),
    ("ADJUDICATOR",
     "ROUTE &rarr; MATCH &rarr; UNBLOCK &rarr; IMPOSSIBLE<br>"
     "IMPOSSIBLE requires a proof; else NEEDS_WORK", "box"),
]


def _render_flow(html: str) -> str:
    """Replace the mermaid source block with a CSS-drawn version of the same graph."""
    m = re.search(r"<pre><code[^>]*>\s*flowchart TD.*?</code></pre>", html, re.S)
    if not m:
        return html
    parts = ['<div class="flow">']
    for i, (head, sub, kind) in enumerate(_FLOW):
        if i:
            parts.append('<div class="arrow">&darr;</div>')
        parts.append(
            f'<div class="node {kind}"><div class="nh">{head}</div>'
            + (f'<div class="ns">{sub}</div>' if sub else "")
            + "</div>"
        )
    parts.append(
        '<div class="feedback">FAIL &mdash; the exact compiler error is injected '
        "<i>verbatim</i> into the next Builder prompt</div></div>"
    )
    return html[: m.start()] + "".join(parts) + html[m.end():]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--md", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--logo", default=str(_ROOT / "frontend/src-tauri/icons/128x128@2x.png"))
    a = ap.parse_args()

    import markdown

    src = Path(a.md).read_text(encoding="utf-8")

    # The first four lines are the cover block in the markdown; lift them into the dark
    # header rather than letting them render as ordinary body text.
    lines = src.splitlines()
    title = lines[0].lstrip("# ").strip()
    def _inline(t: str) -> str:
        """Inline markdown -> HTML. The cover lines are markdown too, and stripping `*`
        only from the ends left `Submitter:** DarthCeltic · **Source:**` on the cover."""
        t = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", t)
        t = re.sub(r"\[(.+?)\]\((.+?)\)", r'<a href="\2">\1</a>', t)
        t = re.sub(r"(?<![\w/])((?:github\.com|huggingface\.co)/[\w.\-/]+)",
                   r'<a href="https://\1">\1</a>', t)
        return t

    tag, meta = "", []
    for ln in lines[1:8]:
        s = ln.strip()
        if not s or s.startswith("---"):
            continue
        if not tag:
            tag = _inline(s.strip("*"))
        else:
            meta.append(_inline(s))
    body_md = "\n".join(lines[8:]) if len(lines) > 8 else src

    html_body = markdown.markdown(
        body_md,
        extensions=["tables", "fenced_code", "sane_lists", "attr_list"],
    )
    # GitHub-flavoured strikethrough is not in python-markdown's core.
    html_body = re.sub(r"~~(.+?)~~", r"<del>\1</del>", html_body)
    # mermaid is not vendored and the renderer is offline, so the fence would
    # otherwise ship as raw diagram SOURCE. Draw the same graph in CSS instead.
    html_body = _render_flow(html_body)

    logo = ""
    lp = Path(a.logo)
    if lp.exists():
        b64 = base64.b64encode(lp.read_bytes()).decode()
        logo = f'<img src="data:image/png;base64,{b64}" alt="">'

    meta_html = "<br>".join(meta)
    doc = (
        f"<!doctype html><html><head><meta charset='utf-8'><style>{CSS}</style></head><body>"
        f"<div class='cover'>{logo}<h1>{title}</h1>"
        f"<div class='tag'>{tag}</div><div class='meta'>{meta_html}</div></div>"
        f"{html_body}</body></html>"
    )

    with tempfile.TemporaryDirectory() as td:
        page = Path(td) / "spec.html"
        page.write_text(doc, encoding="utf-8")
        # The script must live inside frontend/ -- node resolves bare ESM specifiers like
        # 'playwright' relative to the SCRIPT's directory, not the cwd, so a temp-dir script
        # cannot see frontend/node_modules however it is invoked.
        script = _ROOT / "frontend" / "_spec_pdf_render.mjs"
        script.write_text(
            "import { chromium } from 'playwright';\n"
            "const [src, out, footer] = process.argv.slice(2);\n"
            "const b = await chromium.launch();\n"
            "const p = await b.newPage();\n"
            "await p.goto('file:///' + src.replace(/\\\\/g, '/'), "
            "{ waitUntil: 'networkidle' });\n"
            "await p.pdf({ path: out, format: 'A4', printBackground: true,\n"
            "  displayHeaderFooter: true, headerTemplate: '<div></div>',\n"
            "  footerTemplate: footer,\n"
            "  margin: { top: '18mm', bottom: '20mm', left: '0mm', right: '0mm' } });\n"
            "await b.close();\n",
            encoding="utf-8",
        )
        r = subprocess.run(
            ["node", str(script), str(page), str(Path(a.out).resolve()), FOOTER],
            cwd=str(_ROOT / "frontend"), capture_output=True, text=True, timeout=300,
        )
        if r.returncode != 0:
            sys.stderr.write(r.stderr[-2000:] + "\n")
            return 1

    size = Path(a.out).stat().st_size
    print(f"  wrote {a.out}  ({size / 1024:.0f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
