"""
go_validator.py — Determinex Go Output Validator

Validates Go code generated by the data engine by:
1. Stripping markdown fences
2. Extracting or wrapping the student function in a minimal package main scaffold
3. Writing to a temp file inside a temp go.mod module
4. Running `go build .`

Returns (True, "go build OK") on success, (False, "<stderr>") on failure.
"""

from __future__ import annotations

import re
import subprocess
import tempfile
from pathlib import Path

_COMPILE_TIMEOUT = 30  # seconds


def _strip_fences(code: str) -> str:
    """Remove ```go ... ``` or generic ``` ... ``` fences."""
    code = code.strip()
    code = re.sub(r"^```\w*\s*\n", "", code, flags=re.MULTILINE)
    code = re.sub(r"\n```\s*$", "", code, flags=re.MULTILINE)
    return code.strip()


def _ensure_package(code: str) -> str:
    """Ensure 'package main' declaration is present."""
    if not re.search(r"^\s*package\s+\w+", code, re.MULTILINE):
        code = "package main\n\n" + code
    return code


def _ensure_imports(code: str) -> str:
    """
    Inject a common import block if fmt or errors is referenced but not imported.
    This mirrors the pattern used by the wrap_error curriculum prompts.
    """
    has_imports = bool(re.search(r"\bimport\b", code))
    if has_imports:
        return code  # Trust existing imports

    needs_fmt = "fmt." in code
    needs_errors = "errors." in code
    needs_strings = "strings." in code

    if not (needs_fmt or needs_errors or needs_strings):
        return code

    imports = []
    if needs_errors:
        imports.append('\t"errors"')
    if needs_fmt:
        imports.append('\t"fmt"')
    if needs_strings:
        imports.append('\t"strings"')

    block = "import (\n" + "\n".join(imports) + "\n)\n\n"
    # Insert after package declaration
    m = re.search(r"^package\s+\w+.*$", code, re.MULTILINE)
    if m:
        end = m.end()
        code = code[:end] + "\n\n" + block + code[end:].lstrip("\n")
    else:
        code = block + code

    return code


def validate(output: str, task_meta: dict) -> tuple[bool, str]:
    """
    Compile-validate Go output using `go build`.

    Parameters
    ----------
    output    : str   Raw model output (may contain markdown fences / prose).
    task_meta : dict  Curriculum entry metadata (not used for Go compile check).

    Returns
    -------
    (True, "go build OK")  on success
    (False, "<error>")     on failure
    """
    code = _strip_fences(output)

    if len(code) < 10:
        return False, "output too short"
    if "```" in code:
        return False, "unstripped markdown fences remain"

    code = _ensure_package(code)
    code = _ensure_imports(code)

    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            td = Path(tmpdir)
            (td / "go.mod").write_text("module determinex_validate\n\ngo 1.21\n", encoding="utf-8")
            (td / "main.go").write_text(code, encoding="utf-8")

            r = subprocess.run(
                ["go", "build", "."],
                capture_output=True,
                text=True,
                timeout=_COMPILE_TIMEOUT,
                cwd=tmpdir,
            )
            if r.returncode == 0:
                return True, "go build OK"
            stderr = (r.stderr or r.stdout)[:400].replace("\n", " | ")
            return False, f"go build: {stderr}"

    except subprocess.TimeoutExpired:
        return False, "go build timeout"
    except FileNotFoundError:
        return False, "go not on PATH"
    except Exception as e:
        return False, f"go validator error: {e}"
